package org.profamilia.hc.model.dto;



/**
 * CcdetfacveId generated by hbm2java
 */

public class CcdetfacveId  implements java.io.Serializable {



    private Integer cdvnconsec;
    private Integer cdvncondet;


    // Constructors

    /** default constructor */
    public CcdetfacveId() {
    }
    

// HS SEPARADOR CONSTRUCTOR

    

   
    // Property accessors


    public Integer getCdvnconsec() {
        return this.cdvnconsec;
    }
    
    public void setCdvnconsec(
						Integer cdvnconsec) {
        this.cdvnconsec = cdvnconsec;
    }


    public Integer getCdvncondet() {
        return this.cdvncondet;
    }
    
    public void setCdvncondet(
						Integer cdvncondet) {
        this.cdvncondet = cdvncondet;
    }
   








	// no tiene llave compuesta.


}
