package org.profamilia.hc.model.dto;


/**
 * CcdetafactId generated by hbm2java
 */
public class CcdetafactId implements java.io.Serializable {


    private Integer cdfnnumero;
    private Integer cdfnconsec;


    // Constructors

    /** default constructor */
    public CcdetafactId() {
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCdfnnumero() {
        return this.cdfnnumero;
    }

    public void setCdfnnumero(Integer cdfnnumero) {
        this.cdfnnumero = cdfnnumero;
    }


    public Integer getCdfnconsec() {
        return this.cdfnconsec;
    }

    public void setCdfnconsec(Integer cdfnconsec) {
        this.cdfnconsec = cdfnconsec;
    }


    // no tiene llave compuesta.


}
