package org.profamilia.hc.model.dto;


import java.math.BigDecimal;

/**
 * CcdescemplId generated by hbm2java
 */
public class

CcdescemplId implements java.io.Serializable {

    private Integer cdenanno;
    private String cdectipide;
    private BigDecimal cdeanumide;
    private Integer cdengrupo;
    private Integer cdensubgru;
    private String cdecservic;

    // Constructors

    /** default constructor */
    public CcdescemplId() {
    }

    // HS SEPARADOR CONSTRUCTOR

    // Property accessors

    public String getCdecservic() {
        return this.cdecservic;
    }

    public void setCdecservic(String cdecservic) {
        this.cdecservic = cdecservic;
    }

    public Integer getCdengrupo() {
        return this.cdengrupo;
    }

    public void setCdengrupo(Integer cdengrupo) {
        this.cdengrupo = cdengrupo;
    }

    public Integer getCdensubgru() {
        return this.cdensubgru;
    }

    public void setCdensubgru(Integer cdensubgru) {
        this.cdensubgru = cdensubgru;
    }

    public Integer getCdenanno() {
        return this.cdenanno;
    }

    public void setCdenanno(Integer cdenanno) {
        this.cdenanno = cdenanno;
    }

    public String getCdectipide() {
        return cdectipide;
    }

    public void setCdectipide(String cdectipide) {
        this.cdectipide = cdectipide;
    }

    public BigDecimal getCdeanumide() {
        return cdeanumide;
    }

    public void setCdeanumide(BigDecimal cdeanumide) {
        this.cdeanumide = cdeanumide;
    }

    // no tiene llave compuesta.

}
