package org.profamilia.hc.model.dto;

import java.math.BigDecimal;


/**
 * Ccdetfacve generated by hbm2java
 */

public class Ccdetfacve  implements java.io.Serializable {



    private CcdetfacveId id;
    private String cdvcservic;
    private BigDecimal cdvavalser;
    private BigDecimal cdvaivaser;
    private BigDecimal cdvadescto;
    private Integer cdvncantid;
    private BigDecimal cdvavalent;
    private BigDecimal cdvavaltot;
    private String cdvccodcup;
    private String cdvcpaquet;
    private String cdvcswpaqu;
    private BigDecimal cdvavaldon;
    private String cdvcnumlot;

    private Integer version;

	/**
	 * @return the version
	 */
	public final Integer getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public final void setVersion(Integer version) {
		this.version = version;
	}    
    
    
    // Constructors

    /** default constructor */
    public Ccdetfacve() {
    }
    
    /** constructor with id */
    // HS == CcdetfacveId
    

    public Ccdetfacve(CcdetfacveId id) {
        this.id = id;
    }

// HS SEPARADOR CONSTRUCTOR

    

   
    // Property accessors


    public CcdetfacveId getId() {
        return this.id;
    }
    
    public void setId(
						CcdetfacveId id) {
        this.id = id;
    }


    public String getCdvcservic() {
        return this.cdvcservic;
    }
    
    public void setCdvcservic(
						String cdvcservic) {
        this.cdvcservic = cdvcservic;
    }


    public BigDecimal getCdvavalser() {
        return this.cdvavalser;
    }
    
    public void setCdvavalser(
						BigDecimal cdvavalser) {
        this.cdvavalser = cdvavalser;
    }


    public BigDecimal getCdvaivaser() {
        return this.cdvaivaser;
    }
    
    public void setCdvaivaser(
						BigDecimal cdvaivaser) {
        this.cdvaivaser = cdvaivaser;
    }


    public BigDecimal getCdvadescto() {
        return this.cdvadescto;
    }
    
    public void setCdvadescto(
						BigDecimal cdvadescto) {
        this.cdvadescto = cdvadescto;
    }


    public Integer getCdvncantid() {
        return this.cdvncantid;
    }
    
    public void setCdvncantid(
						Integer cdvncantid) {
        this.cdvncantid = cdvncantid;
    }


    public BigDecimal getCdvavalent() {
        return this.cdvavalent;
    }
    
    public void setCdvavalent(
						BigDecimal cdvavalent) {
        this.cdvavalent = cdvavalent;
    }


    public BigDecimal getCdvavaltot() {
        return this.cdvavaltot;
    }
    
    public void setCdvavaltot(
						BigDecimal cdvavaltot) {
        this.cdvavaltot = cdvavaltot;
    }


    public String getCdvccodcup() {
        return this.cdvccodcup;
    }
    
    public void setCdvccodcup(
						String cdvccodcup) {
        this.cdvccodcup = cdvccodcup;
    }


    public String getCdvcpaquet() {
        return this.cdvcpaquet;
    }
    
    public void setCdvcpaquet(
						String cdvcpaquet) {
        this.cdvcpaquet = cdvcpaquet;
    }


    public String getCdvcswpaqu() {
        return this.cdvcswpaqu;
    }
    
    public void setCdvcswpaqu(
						String cdvcswpaqu) {
        this.cdvcswpaqu = cdvcswpaqu;
    }

    
    public BigDecimal getCdvavaldon() {
        return this.cdvavaldon;
    }
    
    public void setCdvavaldon(
						BigDecimal cdvavaldon) {
        this.cdvavaldon = cdvavaldon;
    }

    public String getCdvcnumlot() {
    	return this.cdvcnumlot;
    }
    
    public void setCdvcnumlot(
    					String cdvcnumlot) {
    	this.cdvcnumlot = cdvcnumlot;
    }


	
    public Integer getCdvnconsec() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCdvnconsec();
    }

    public void setCdvnconsec(Integer cdvnconsec) {
        if (this.id == null) {
            this.id = new CcdetfacveId();
        }
        this.id.setCdvnconsec(cdvnconsec);
    }
    public Integer getCdvncondet() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCdvncondet();
    }

    public void setCdvncondet(Integer cdvncondet) {
        if (this.id == null) {
            this.id = new CcdetfacveId();
        }
        this.id.setCdvncondet(cdvncondet);
    }



}
