package org.profamilia.hc.model.dto;

import java.math.BigDecimal;


/**
 * Ccdetafact generated by hbm2java
 */
public class

Ccdetafact implements java.io.Serializable {


    private CcdetafactId id;
    private String cdfcservic;
    private String cdfccodent;
    private BigDecimal cdfavalser;
    private BigDecimal cdfaivaser;
    private BigDecimal cdfadescto;
    private Integer cdfncantid;
    private BigDecimal cdfavalent;
    private BigDecimal cdfavaltot;
    private Integer cdfnnumite;
    private String cdfcpaquet;
    private String cdfcswpaqu;
    private BigDecimal cdfavaldon;
    private String cdfcnumlot;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Ccdetafact() {
    }

    /** constructor with id */
    public
    // HS == CcdetafactId


    Ccdetafact(CcdetafactId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CcdetafactId getId() {
        return this.id;
    }

    public void setId(CcdetafactId id) {
        this.id = id;
    }


    public String getCdfcservic() {
        return this.cdfcservic;
    }

    public void setCdfcservic(String cdfcservic) {
        this.cdfcservic = cdfcservic;
    }


    public String getCdfccodent() {
        return this.cdfccodent;
    }

    public void setCdfccodent(String cdfccodent) {
        this.cdfccodent = cdfccodent;
    }


    public BigDecimal getCdfavalser() {
        return this.cdfavalser;
    }

    public void setCdfavalser(BigDecimal cdfavalser) {
        this.cdfavalser = cdfavalser;
    }


    public BigDecimal getCdfaivaser() {
        return this.cdfaivaser;
    }

    public void setCdfaivaser(BigDecimal cdfaivaser) {
        this.cdfaivaser = cdfaivaser;
    }


    public BigDecimal getCdfadescto() {
        return this.cdfadescto;
    }

    public void setCdfadescto(BigDecimal cdfadescto) {
        this.cdfadescto = cdfadescto;
    }


    public Integer getCdfncantid() {
        return this.cdfncantid;
    }

    public void setCdfncantid(Integer cdfncantid) {
        this.cdfncantid = cdfncantid;
    }


    public BigDecimal getCdfavalent() {
        return this.cdfavalent;
    }

    public void setCdfavalent(BigDecimal cdfavalent) {
        this.cdfavalent = cdfavalent;
    }


    public BigDecimal getCdfavaltot() {
        return this.cdfavaltot;
    }

    public void setCdfavaltot(BigDecimal cdfavaltot) {
        this.cdfavaltot = cdfavaltot;
    }


    public Integer getCdfnnumite() {
        return this.cdfnnumite;
    }

    public void setCdfnnumite(Integer cdfnnumite) {
        this.cdfnnumite = cdfnnumite;
    }


    public String getCdfcpaquet() {
        return this.cdfcpaquet;
    }

    public void setCdfcpaquet(String cdfcpaquet) {
        this.cdfcpaquet = cdfcpaquet;
    }


    public String getCdfcswpaqu() {
        return this.cdfcswpaqu;
    }

    public void setCdfcswpaqu(String cdfcswpaqu) {
        this.cdfcswpaqu = cdfcswpaqu;
    }

    public BigDecimal getCdfavaldon() {
        return this.cdfavaldon;
    }

    public void setCdfavaldon(BigDecimal cdfavaldon) {
        this.cdfavaldon = cdfavaldon;
    }

    public String getCdfcnumlot() {
        return this.cdfcnumlot;
    }

    public void setCdfcnumlot(String cdfcnumlot) {
        this.cdfcnumlot = cdfcnumlot;
    }


    public Integer getCdfnnumero() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCdfnnumero();
    }

    public void setCdfnnumero(Integer cdfnnumero) {
        if (this.id == null) {
            this.id = new CcdetafactId();
        }
        this.id.setCdfnnumero(cdfnnumero);
    }

    public Integer getCdfnconsec() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCdfnconsec();
    }

    public void setCdfnconsec(Integer cdfnconsec) {
        if (this.id == null) {
            this.id = new CcdetafactId();
        }
        this.id.setCdfnconsec(cdfnconsec);
    }


}
