package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Ccfactserv generated by hbm2java
 */
public class Ccfactserv implements java.io.Serializable {


    private Integer cfsnnumero;
    private Integer cfsnnumfac;
    private Integer cfsnclinic;
    private Integer cfsnclifac;
    private Date cfsdfecreg;
    private Date cfsthorreg;
    private String cfscusuari;
    private Integer cfsncontra;
    private Integer cfsnprogra;
    private BigDecimal cfsasubtot;
    private BigDecimal cfsaabono;
    private String cfscpacien;
    private Integer cfsnbodega;
    private BigDecimal cfsanumrp;
    private BigDecimal cfsaiva;
    private BigDecimal cfsadescto;
    private BigDecimal cfsavalent;
    private Integer cfsnestado;
    private String cfsctermin;
    private String cfsctipide;
    private BigDecimal cfsanumide;
    private Date cfsdfecrem;
    private String cfscremite;
    private Integer cfsnnumcue;
    private String cfscimpres;
    private Integer cfsndonant;
    private String cfscgenero;
    private String cfscnumrem;
    private BigDecimal cfsavaldon;
    private BigDecimal cfslusuario;


    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }


    // Constructors

    /** default constructor */
    public Ccfactserv() {
    }

    /** constructor with id */
    public
    // HS == Integer


    Ccfactserv(Integer cfsnnumero) {
        this.cfsnnumero = cfsnnumero;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCfsnnumero() {
        return this.cfsnnumero;
    }

    public void setCfsnnumero(Integer cfsnnumero) {
        this.cfsnnumero = cfsnnumero;
    }


    public Integer getCfsnnumfac() {
        return this.cfsnnumfac;
    }

    public void setCfsnnumfac(Integer cfsnnumfac) {
        this.cfsnnumfac = cfsnnumfac;
    }


    public Integer getCfsnclinic() {
        return this.cfsnclinic;
    }

    public void setCfsnclinic(Integer cfsnclinic) {
        this.cfsnclinic = cfsnclinic;
    }


    public Integer getCfsnclifac() {
        return this.cfsnclifac;
    }

    public void setCfsnclifac(Integer cfsnclifac) {
        this.cfsnclifac = cfsnclifac;
    }


    public Date getCfsdfecreg() {
        return this.cfsdfecreg;
    }

    public void setCfsdfecreg(Date cfsdfecreg) {
        this.cfsdfecreg = cfsdfecreg;
    }


    public Date getCfsthorreg() {
        return this.cfsthorreg;
    }

    public void setCfsthorreg(Date cfsthorreg) {
        this.cfsthorreg = cfsthorreg;
    }


    public String getCfscusuari() {
        return this.cfscusuari;
    }

    public void setCfscusuari(String cfscusuari) {
        this.cfscusuari = cfscusuari;
    }


    public Integer getCfsncontra() {
        return this.cfsncontra;
    }

    public void setCfsncontra(Integer cfsncontra) {
        this.cfsncontra = cfsncontra;
    }


    public Integer getCfsnprogra() {
        return this.cfsnprogra;
    }

    public void setCfsnprogra(Integer cfsnprogra) {
        this.cfsnprogra = cfsnprogra;
    }


    public BigDecimal getCfsasubtot() {
        return this.cfsasubtot;
    }

    public void setCfsasubtot(BigDecimal cfsasubtot) {
        this.cfsasubtot = cfsasubtot;
    }


    public BigDecimal getCfsaabono() {
        return this.cfsaabono;
    }

    public void setCfsaabono(BigDecimal cfsaabono) {
        this.cfsaabono = cfsaabono;
    }


    public String getCfscpacien() {
        return this.cfscpacien;
    }

    public void setCfscpacien(String cfscpacien) {
        this.cfscpacien = cfscpacien;
    }


    public Integer getCfsnbodega() {
        return this.cfsnbodega;
    }

    public void setCfsnbodega(Integer cfsnbodega) {
        this.cfsnbodega = cfsnbodega;
    }


    public BigDecimal getCfsanumrp() {
        return this.cfsanumrp;
    }

    public void setCfsanumrp(BigDecimal cfsanumrp) {
        this.cfsanumrp = cfsanumrp;
    }


    public BigDecimal getCfsaiva() {
        return this.cfsaiva;
    }

    public void setCfsaiva(BigDecimal cfsaiva) {
        this.cfsaiva = cfsaiva;
    }


    public BigDecimal getCfsadescto() {
        return this.cfsadescto;
    }

    public void setCfsadescto(BigDecimal cfsadescto) {
        this.cfsadescto = cfsadescto;
    }


    public BigDecimal getCfsavalent() {
        return this.cfsavalent;
    }

    public void setCfsavalent(BigDecimal cfsavalent) {
        this.cfsavalent = cfsavalent;
    }


    public Integer getCfsnestado() {
        return this.cfsnestado;
    }

    public void setCfsnestado(Integer cfsnestado) {
        this.cfsnestado = cfsnestado;
    }


    public String getCfsctermin() {
        return this.cfsctermin;
    }

    public void setCfsctermin(String cfsctermin) {
        this.cfsctermin = cfsctermin;
    }


    public String getCfsctipide() {
        return this.cfsctipide;
    }

    public void setCfsctipide(String cfsctipide) {
        this.cfsctipide = cfsctipide;
    }


    public BigDecimal getCfsanumide() {
        return this.cfsanumide;
    }

    public void setCfsanumide(BigDecimal cfsanumide) {
        this.cfsanumide = cfsanumide;
    }


    public Date getCfsdfecrem() {
        return this.cfsdfecrem;
    }

    public void setCfsdfecrem(Date cfsdfecrem) {
        this.cfsdfecrem = cfsdfecrem;
    }


    public String getCfscremite() {
        return this.cfscremite;
    }

    public void setCfscremite(String cfscremite) {
        this.cfscremite = cfscremite;
    }


    public Integer getCfsnnumcue() {
        return this.cfsnnumcue;
    }

    public void setCfsnnumcue(Integer cfsnnumcue) {
        this.cfsnnumcue = cfsnnumcue;
    }


    public String getCfscimpres() {
        return this.cfscimpres;
    }

    public void setCfscimpres(String cfscimpres) {
        this.cfscimpres = cfscimpres;
    }


    public Integer getCfsndonant() {
        return this.cfsndonant;
    }

    public void setCfsndonant(Integer cfsndonant) {
        this.cfsndonant = cfsndonant;
    }


    public String getCfscgenero() {
        return this.cfscgenero;
    }

    public void setCfscgenero(String cfscgenero) {
        this.cfscgenero = cfscgenero;
    }


    public String getCfscnumrem() {
        return this.cfscnumrem;
    }

    public void setCfscnumrem(String cfscnumrem) {
        this.cfscnumrem = cfscnumrem;
    }


    public BigDecimal getCfsavaldon() {
        return this.cfsavaldon;
    }

    public void setCfsavaldon(BigDecimal cfsavaldon) {
        this.cfsavaldon = cfsavaldon;
    }

    public BigDecimal getCfslusuario() {
        return cfslusuario;
    }

    public void setCfslusuario(BigDecimal cfslusuario) {
        this.cfslusuario = cfslusuario;
    }


    // no tiene llave compuesta.


}
