package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Ccfactvent generated by hbm2java
 */
public class Ccfactvent implements java.io.Serializable {


    private Integer cfvnconsec;
    private Integer cfvnclinic;
    private Integer cfvntipdoc;
    private Integer cfvnnumero;
    private Integer cfvnclifac;
    private Date cfvdfecreg;
    private Date cfvthorreg;
    private String cfvcusuari;
    private Integer cfvnprogra;
    private Integer cfvndonant;
    private Integer cfvntipusu;
    private BigDecimal cfvasubtot;
    private BigDecimal cfvaabono;
    private Integer cfvnbodega;
    private BigDecimal cfvaiva;
    private BigDecimal cfvadescto;
    private BigDecimal cfvavalent;
    private Integer cfvnestado;
    private String cfvctermin;
    private String cfvctipide;
    private BigDecimal cfvanumide;
    private String cfvcprinom;
    private String cfvcsegnom;
    private String cfvcpriape;
    private String cfvcsegape;
    private String cfvcusureg;
    private Date cfvdfecfac;
    private Date cfvthorfac;
    private String cfvcgenero;
    private BigDecimal cfvavaldon;
    private Long cfvlusuario;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }


    // Constructors

    /** default constructor */
    public Ccfactvent() {
    }

    /** constructor with id */
    public
    // HS == Integer


    Ccfactvent(Integer cfvnconsec) {
        this.cfvnconsec = cfvnconsec;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCfvnconsec() {
        return this.cfvnconsec;
    }

    public void setCfvnconsec(Integer cfvnconsec) {
        this.cfvnconsec = cfvnconsec;
    }


    public Integer getCfvnclinic() {
        return this.cfvnclinic;
    }

    public void setCfvnclinic(Integer cfvnclinic) {
        this.cfvnclinic = cfvnclinic;
    }


    public Integer getCfvntipdoc() {
        return this.cfvntipdoc;
    }

    public void setCfvntipdoc(Integer cfvntipdoc) {
        this.cfvntipdoc = cfvntipdoc;
    }


    public Integer getCfvnnumero() {
        return this.cfvnnumero;
    }

    public void setCfvnnumero(Integer cfvnnumero) {
        this.cfvnnumero = cfvnnumero;
    }


    public Integer getCfvnclifac() {
        return this.cfvnclifac;
    }

    public void setCfvnclifac(Integer cfvnclifac) {
        this.cfvnclifac = cfvnclifac;
    }


    public Date getCfvdfecreg() {
        return this.cfvdfecreg;
    }

    public void setCfvdfecreg(Date cfvdfecreg) {
        this.cfvdfecreg = cfvdfecreg;
    }


    public Date getCfvthorreg() {
        return this.cfvthorreg;
    }

    public void setCfvthorreg(Date cfvthorreg) {
        this.cfvthorreg = cfvthorreg;
    }


    public String getCfvcusuari() {
        return this.cfvcusuari;
    }

    public void setCfvcusuari(String cfvcusuari) {
        this.cfvcusuari = cfvcusuari;
    }


    public Integer getCfvnprogra() {
        return this.cfvnprogra;
    }

    public void setCfvnprogra(Integer cfvnprogra) {
        this.cfvnprogra = cfvnprogra;
    }


    public Integer getCfvndonant() {
        return this.cfvndonant;
    }

    public void setCfvndonant(Integer cfvndonant) {
        this.cfvndonant = cfvndonant;
    }


    public Integer getCfvntipusu() {
        return this.cfvntipusu;
    }

    public void setCfvntipusu(Integer cfvntipusu) {
        this.cfvntipusu = cfvntipusu;
    }


    public BigDecimal getCfvasubtot() {
        return this.cfvasubtot;
    }

    public void setCfvasubtot(BigDecimal cfvasubtot) {
        this.cfvasubtot = cfvasubtot;
    }


    public BigDecimal getCfvaabono() {
        return this.cfvaabono;
    }

    public void setCfvaabono(BigDecimal cfvaabono) {
        this.cfvaabono = cfvaabono;
    }


    public Integer getCfvnbodega() {
        return this.cfvnbodega;
    }

    public void setCfvnbodega(Integer cfvnbodega) {
        this.cfvnbodega = cfvnbodega;
    }


    public BigDecimal getCfvaiva() {
        return this.cfvaiva;
    }

    public void setCfvaiva(BigDecimal cfvaiva) {
        this.cfvaiva = cfvaiva;
    }


    public BigDecimal getCfvadescto() {
        return this.cfvadescto;
    }

    public void setCfvadescto(BigDecimal cfvadescto) {
        this.cfvadescto = cfvadescto;
    }


    public BigDecimal getCfvavalent() {
        return this.cfvavalent;
    }

    public void setCfvavalent(BigDecimal cfvavalent) {
        this.cfvavalent = cfvavalent;
    }


    public Integer getCfvnestado() {
        return this.cfvnestado;
    }

    public void setCfvnestado(Integer cfvnestado) {
        this.cfvnestado = cfvnestado;
    }


    public String getCfvctermin() {
        return this.cfvctermin;
    }

    public void setCfvctermin(String cfvctermin) {
        this.cfvctermin = cfvctermin;
    }


    public String getCfvctipide() {
        return this.cfvctipide;
    }

    public void setCfvctipide(String cfvctipide) {
        this.cfvctipide = cfvctipide;
    }


    public BigDecimal getCfvanumide() {
        return this.cfvanumide;
    }

    public void setCfvanumide(BigDecimal cfvanumide) {
        this.cfvanumide = cfvanumide;
    }


    public String getCfvcprinom() {
        return this.cfvcprinom;
    }

    public void setCfvcprinom(String cfvcprinom) {
        this.cfvcprinom = cfvcprinom;
    }


    public String getCfvcsegnom() {
        return this.cfvcsegnom;
    }

    public void setCfvcsegnom(String cfvcsegnom) {
        this.cfvcsegnom = cfvcsegnom;
    }


    public String getCfvcpriape() {
        return this.cfvcpriape;
    }

    public void setCfvcpriape(String cfvcpriape) {
        this.cfvcpriape = cfvcpriape;
    }


    public String getCfvcsegape() {
        return this.cfvcsegape;
    }

    public void setCfvcsegape(String cfvcsegape) {
        this.cfvcsegape = cfvcsegape;
    }


    public String getCfvcusureg() {
        return this.cfvcusureg;
    }

    public void setCfvcusureg(String cfvcusureg) {
        this.cfvcusureg = cfvcusureg;
    }


    public Date getCfvdfecfac() {
        return this.cfvdfecfac;
    }

    public void setCfvdfecfac(Date cfvdfecfac) {
        this.cfvdfecfac = cfvdfecfac;
    }


    public Date getCfvthorfac() {
        return this.cfvthorfac;
    }

    public void setCfvthorfac(Date cfvthorfac) {
        this.cfvthorfac = cfvthorfac;
    }


    public String getCfvcgenero() {
        return this.cfvcgenero;
    }

    public void setCfvcgenero(String cfvcgenero) {
        this.cfvcgenero = cfvcgenero;
    }


    public BigDecimal getCfvavaldon() {
        return this.cfvavaldon;
    }

    public void setCfvavaldon(BigDecimal cfvavaldon) {
        this.cfvavaldon = cfvavaldon;
    }

    public Long getCfvlusuario() {
        return cfvlusuario;
    }

    public void setCfvlusuario(Long cfvlusuario) {
        this.cfvlusuario = cfvlusuario;
    }

    // no tiene llave compuesta.

}
