package org.profamilia.hc.model.dto;


import java.math.BigDecimal;

/**
 * CcdescemplId generated by hbm2java
 */

public class ChmedicamentId implements java.io.Serializable {


    /** identifier field */
    private Long hmelconsulta;

    /** identifier field */
    private Integer hmenconsecut;
    
    /** identifier field */
    private Long hmelconsuasoci;


	// Constructors

	/** default constructor */
	public ChmedicamentId() {
	}


    public void setHmelconsulta(Long hmelconsulta) {
        this.hmelconsulta = hmelconsulta;
    }

    public Long getHmelconsulta() {
        return hmelconsulta;
    }

    public void setHmenconsecut(Integer hmenconsecut) {
        this.hmenconsecut = hmenconsecut;
    }

    public Integer getHmenconsecut() {
        return hmenconsecut;
    }

    public void setHmelconsuasoci(Long hmelconsuasoci) {
        this.hmelconsuasoci = hmelconsuasoci;
    }

    public Long getHmelconsuasoci() {
        return hmelconsuasoci;
    }
}
