package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cpclinica generated by hbm2java
 */
public class Cicotizsap implements java.io.Serializable {


    private Long  ccslnumero;
    
    private String ccsctipoident; 
    
    private Long ccsanumerident; 
    
    private String ccscservicio; 
    
    private Long ccslusuario; 
    
    private Date ccsdfechacotiz; 
    
    private Date ccsdhoracotiz; 
    
    private Integer ccsnclinica; 
    
    private Integer ccsncantidad; 
    
    private String ccsclugarservi; 
    
    private String ccsctipoventa; 
   
    
    private Integer version;
    
    /** default constructor */
    public Cicotizsap() {
    }


    /**
     * @param ccslnumero
     */
    public void setCcslnumero(Long ccslnumero) {
        this.ccslnumero = ccslnumero;
    }

    /**
     * @return
     */
    public Long getCcslnumero() {
        return ccslnumero;
    }

    /**
     * @param ccsctipoident
     */
    public void setCcsctipoident(String ccsctipoident) {
        this.ccsctipoident = ccsctipoident;
    }

    /**
     * @return
     */
    public String getCcsctipoident() {
        return ccsctipoident;
    }

    /**
     * @param ccsanumerident
     */
    public void setCcsanumerident(Long ccsanumerident) {
        this.ccsanumerident = ccsanumerident;
    }

    /**
     * @return
     */
    public Long getCcsanumerident() {
        return ccsanumerident;
    }

    /**
     * @param ccscservicio
     */
    public void setCcscservicio(String ccscservicio) {
        this.ccscservicio = ccscservicio;
    }

    /**
     * @return
     */
    public String getCcscservicio() {
        return ccscservicio;
    }

    /**
     * @param ccslusuario
     */
    public void setCcslusuario(Long ccslusuario) {
        this.ccslusuario = ccslusuario;
    }

    /**
     * @return
     */
    public Long getCcslusuario() {
        return ccslusuario;
    }

    /**
     * @param ccsdfechacotiz
     */
    public void setCcsdfechacotiz(Date ccsdfechacotiz) {
        this.ccsdfechacotiz = ccsdfechacotiz;
    }

    /**
     * @return
     */
    public Date getCcsdfechacotiz() {
        return ccsdfechacotiz;
    }

    /**
     * @param ccsdhoracotiz
     */
    public void setCcsdhoracotiz(Date ccsdhoracotiz) {
        this.ccsdhoracotiz = ccsdhoracotiz;
    }

    /**
     * @return
     */
    public Date getCcsdhoracotiz() {
        return ccsdhoracotiz;
    }

    /**
     * @param ccsnclinica
     */
    public void setCcsnclinica(Integer ccsnclinica) {
        this.ccsnclinica = ccsnclinica;
    }

    /**
     * @return
     */
    public Integer getCcsnclinica() {
        return ccsnclinica;
    }

    /**
     * @param ccsncantidad
     */
    public void setCcsncantidad(Integer ccsncantidad) {
        this.ccsncantidad = ccsncantidad;
    }

    /**
     * @return
     */
    public Integer getCcsncantidad() {
        return ccsncantidad;
    }

    /**
     * @param ccsclugarservi
     */
    public void setCcsclugarservi(String ccsclugarservi) {
        this.ccsclugarservi = ccsclugarservi;
    }

    /**
     * @return
     */
    public String getCcsclugarservi() {
        return ccsclugarservi;
    }

    /**
     * @param ccsctipoventa
     */
    public void setCcsctipoventa(String ccsctipoventa) {
        this.ccsctipoventa = ccsctipoventa;
    }

    /**
     * @return
     */
    public String getCcsctipoventa() {
        return ccsctipoventa;
    }

    /**
     * @param version
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * @return
     */
    public Integer getVersion() {
        return version;
    }

  
}
