package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

/**
 * CnespermogId generated by hbm2java
 */

public class CncapaespeId implements java.io.Serializable {

	private Integer ccenclinic;
	private Integer ccennumero;

	// Constructors

	/** default constructor */
	public CncapaespeId() {
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public Integer getCcenclinic() {
		return this.ccenclinic;
	}

	public void setCcenclinic(Integer ccenclinic) {
		this.ccenclinic = ccenclinic;
	}

	public Integer getCcennumero() {
		return this.ccennumero;
	}

	public void setCcennumero(Integer ccennumero) {
		this.ccennumero = ccennumero;
	}

	// no tiene llave compuesta.

}
