package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

/**
 * CnespermogId generated by hbm2java
 */

public class CnespermogId implements java.io.Serializable {

	private Integer cesnclinic;
	private Integer cesnnumero;

	// Constructors

	/** default constructor */
	public CnespermogId() {
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public Integer getCesnclinic() {
		return this.cesnclinic;
	}

	public void setCesnclinic(Integer cesnclinic) {
		this.cesnclinic = cesnclinic;
	}

	public Integer getCesnnumero() {
		return this.cesnnumero;
	}

	public void setCesnnumero(Integer cesnnumero) {
		this.cesnnumero = cesnnumero;
	}

	// no tiene llave compuesta.

}
