package org.profamilia.hc.model.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cnespermog generated by hbm2java
 */

public class Cnespermog implements java.io.Serializable {

	/**
	 * serialVersionUID class Cnespermog
	 */
	private static final long serialVersionUID = 761154282710002686L;
	
	private CnespermogId id;
        private Long cesnconcli;
        private String cesctipide;
        private BigDecimal cesanumide;
        private String cescpacien;
        private Integer cesnedapac;
        private String cescremite;
        private Date cesdfecesp;
        private Integer cesndiaabs;
        private String cescparoti;
        private String cescorquit;
        private Integer cesnhijos;
        private String cescfumar;
        private String cescets;
        private String cescmedact;
        private String cesccirugi;
        private String cescurolog;
        private String cescinfert;
        private String cescotros;
        private String cescviscos;
        private String cesccolor;
        private Integer cesncantid;
        private Integer cesnprorap;
        private Integer cesnprolen;
        private Integer cesnpendul;
        private Integer cesninmovi;
        private Integer cesnvivos;
        private Integer cesnmuerto;
        private String cescleucoc;
        private String cescpiocit;
        private String ceschemati;
        private Integer cesnligelo;
        private Integer cesnmarelo;
        private Integer cesnanoacr;
        private Integer cesnmacroc;
        private Integer cesnmicroc;
        private Integer cesndobcab;
        private Integer cesnangula;
        private Integer cesnflaenr;
        private Integer cesndobfla;
        private Integer cesnnormal;
        private Integer cesnanomul;
        private String cesxobserv;
        private String cescusureg;
        private Date cesdfecreg;
        private Integer cesntipesp;
        private BigDecimal cesavolume;
        private BigDecimal cesatotal;
        private Integer cesnprogre;
        private Integer cesnanorma;
        private Integer cesnanocab;
        private Integer cesnanopie;
        private Integer cesnanofla;
	private Integer version;
        private String cescoligoz;
        private String cescasteno;
        private String cescterato;
        private String cescnormoz;

	/**
	 * @return the version
	 */
	public final Integer getVersion() {
		return version;
	}

	/**
	 * @param version
	 *            the version to set
	 */
	public final void setVersion(Integer version) {
		this.version = version;
	}

	// Constructors

	/** default constructor */
	public Cnespermog() {
            id = new CnespermogId();
	}

	/** constructor with id */
	// HS == CnespermogId
	public Cnespermog(CnespermogId id) {
		this.id = id;
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public CnespermogId getId() {
        if(id == null){
            id = new CnespermogId();
        }
        
		return this.id;
	}

	public void setId(CnespermogId id) {
	    if(id == null){
	        id = new CnespermogId();
	    }
		this.id = id;
	}

	public Integer getCesnclinic() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCesnclinic();
	}

	public void setCesnclinic(Integer cesnclinic) {
		if (this.id == null) {
			this.id = new CnespermogId();
		}
		this.id.setCesnclinic(cesnclinic);
	}

	public Integer getCesnnumero() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCesnnumero();
	}

	public void setCesnnumero(Integer cesnnumero) {
		if (this.id == null) {
			this.id = new CnespermogId();
		}
		this.id.setCesnnumero(cesnnumero);
	}



    public void setCesctipide(String cesctipide) {
        this.cesctipide = cesctipide;
    }

    public String getCesctipide() {
        return cesctipide;
    }

    public void setCesanumide(BigDecimal cesanumide) {
        this.cesanumide = cesanumide;
    }

    public BigDecimal getCesanumide() {
        return cesanumide;
    }

    public void setCescpacien(String cescpacien) {
        this.cescpacien = cescpacien;
    }

    public String getCescpacien() {
        return cescpacien;
    }

    public void setCesnedapac(Integer cesnedapac) {
        this.cesnedapac = cesnedapac;
    }

    public Integer getCesnedapac() {
        return cesnedapac;
    }

    public void setCescremite(String cescremite) {
        this.cescremite = cescremite;
    }

    public String getCescremite() {
        return cescremite;
    }

    public void setCesdfecesp(Date cesdfecesp) {
        this.cesdfecesp = cesdfecesp;
    }

    public Date getCesdfecesp() {
        return cesdfecesp;
    }

    public void setCesndiaabs(Integer cesndiaabs) {
        this.cesndiaabs = cesndiaabs;
    }

    public Integer getCesndiaabs() {
        return cesndiaabs;
    }

    public void setCescparoti(String cescparoti) {
        this.cescparoti = cescparoti;
    }

    public String getCescparoti() {
        return cescparoti;
    }

    public void setCescorquit(String cescorquit) {
        this.cescorquit = cescorquit;
    }

    public String getCescorquit() {
        return cescorquit;
    }

    public void setCesnhijos(Integer cesnhijos) {
        this.cesnhijos = cesnhijos;
    }

    public Integer getCesnhijos() {
        return cesnhijos;
    }

    public void setCescfumar(String cescfumar) {
        this.cescfumar = cescfumar;
    }

    public String getCescfumar() {
        return cescfumar;
    }

    public void setCescets(String cescets) {
        this.cescets = cescets;
    }

    public String getCescets() {
        return cescets;
    }

    public void setCescmedact(String cescmedact) {
        this.cescmedact = cescmedact;
    }

    public String getCescmedact() {
        return cescmedact;
    }

    public void setCesccirugi(String cesccirugi) {
        this.cesccirugi = cesccirugi;
    }

    public String getCesccirugi() {
        return cesccirugi;
    }

    public void setCescurolog(String cescurolog) {
        this.cescurolog = cescurolog;
    }

    public String getCescurolog() {
        return cescurolog;
    }

    public void setCescinfert(String cescinfert) {
        this.cescinfert = cescinfert;
    }

    public String getCescinfert() {
        return cescinfert;
    }

    public void setCescotros(String cescotros) {
        this.cescotros = cescotros;
    }

    public String getCescotros() {
        return cescotros;
    }

    public void setCescviscos(String cescviscos) {
        this.cescviscos = cescviscos;
    }

    public String getCescviscos() {
        return cescviscos;
    }

    public void setCesccolor(String cesccolor) {
        this.cesccolor = cesccolor;
    }

    public String getCesccolor() {
        return cesccolor;
    }

    public void setCesncantid(Integer cesncantid) {
        this.cesncantid = cesncantid;
    }

    public Integer getCesncantid() {
        return cesncantid;
    }

    public void setCesnprorap(Integer cesnprorap) {
        this.cesnprorap = cesnprorap;
    }

    public Integer getCesnprorap() {
        return cesnprorap;
    }

    public void setCesnprolen(Integer cesnprolen) {
        this.cesnprolen = cesnprolen;
    }

    public Integer getCesnprolen() {
        return cesnprolen;
    }

    public void setCesnpendul(Integer cesnpendul) {
        this.cesnpendul = cesnpendul;
    }

    public Integer getCesnpendul() {
        return cesnpendul;
    }

    public void setCesninmovi(Integer cesninmovi) {
        this.cesninmovi = cesninmovi;
    }

    public Integer getCesninmovi() {
        return cesninmovi;
    }

    public void setCesnvivos(Integer cesnvivos) {
        this.cesnvivos = cesnvivos;
    }

    public Integer getCesnvivos() {
        return cesnvivos;
    }

    public void setCesnmuerto(Integer cesnmuerto) {
        this.cesnmuerto = cesnmuerto;
    }

    public Integer getCesnmuerto() {
        return cesnmuerto;
    }

    public void setCescleucoc(String cescleucoc) {
        this.cescleucoc = cescleucoc;
    }

    public String getCescleucoc() {
        return cescleucoc;
    }

    public void setCescpiocit(String cescpiocit) {
        this.cescpiocit = cescpiocit;
    }

    public String getCescpiocit() {
        return cescpiocit;
    }

    public void setCeschemati(String ceschemati) {
        this.ceschemati = ceschemati;
    }

    public String getCeschemati() {
        return ceschemati;
    }

    public void setCesnligelo(Integer cesnligelo) {
        this.cesnligelo = cesnligelo;
    }

    public Integer getCesnligelo() {
        return cesnligelo;
    }

    public void setCesnmarelo(Integer cesnmarelo) {
        this.cesnmarelo = cesnmarelo;
    }

    public Integer getCesnmarelo() {
        return cesnmarelo;
    }

    public void setCesnanoacr(Integer cesnanoacr) {
        this.cesnanoacr = cesnanoacr;
    }

    public Integer getCesnanoacr() {
        return cesnanoacr;
    }

    public void setCesnmacroc(Integer cesnmacroc) {
        this.cesnmacroc = cesnmacroc;
    }

    public Integer getCesnmacroc() {
        return cesnmacroc;
    }

    public void setCesnmicroc(Integer cesnmicroc) {
        this.cesnmicroc = cesnmicroc;
    }

    public Integer getCesnmicroc() {
        return cesnmicroc;
    }

    public void setCesndobcab(Integer cesndobcab) {
        this.cesndobcab = cesndobcab;
    }

    public Integer getCesndobcab() {
        return cesndobcab;
    }

    public void setCesnangula(Integer cesnangula) {
        this.cesnangula = cesnangula;
    }

    public Integer getCesnangula() {
        return cesnangula;
    }

    public void setCesnflaenr(Integer cesnflaenr) {
        this.cesnflaenr = cesnflaenr;
    }

    public Integer getCesnflaenr() {
        return cesnflaenr;
    }

    public void setCesndobfla(Integer cesndobfla) {
        this.cesndobfla = cesndobfla;
    }

    public Integer getCesndobfla() {
        return cesndobfla;
    }

    public void setCesnnormal(Integer cesnnormal) {
        this.cesnnormal = cesnnormal;
    }

    public Integer getCesnnormal() {
        return cesnnormal;
    }

    public void setCesnanomul(Integer cesnanomul) {
        this.cesnanomul = cesnanomul;
    }

    public Integer getCesnanomul() {
        return cesnanomul;
    }

    public void setCesxobserv(String cesxobserv) {
        this.cesxobserv = cesxobserv;
    }

    public String getCesxobserv() {
        return cesxobserv;
    }

    public void setCescusureg(String cescusureg) {
        this.cescusureg = cescusureg;
    }

    public String getCescusureg() {
        return cescusureg;
    }

    public void setCesdfecreg(Date cesdfecreg) {
        this.cesdfecreg = cesdfecreg;
    }

    public Date getCesdfecreg() {
        return cesdfecreg;
    }

    public void setCesntipesp(Integer cesntipesp) {
        this.cesntipesp = cesntipesp;
    }

    public Integer getCesntipesp() {
        return cesntipesp;
    }

    public void setCesavolume(BigDecimal cesavolume) {
        this.cesavolume = cesavolume;
    }

    public BigDecimal getCesavolume() {
        return cesavolume;
    }

    public void setCesatotal(BigDecimal cesatotal) {
        this.cesatotal = cesatotal;
    }

    public BigDecimal getCesatotal() {
        return cesatotal;
    }

    public void setCesnprogre(Integer cesnprogre) {
        this.cesnprogre = cesnprogre;
    }

    public Integer getCesnprogre() {
        return cesnprogre;
    }

    public void setCesnanorma(Integer cesnanorma) {
        this.cesnanorma = cesnanorma;
    }

    public Integer getCesnanorma() {
        return cesnanorma;
    }

    public void setCesnanocab(Integer cesnanocab) {
        this.cesnanocab = cesnanocab;
    }

    public Integer getCesnanocab() {
        return cesnanocab;
    }

    public void setCesnanopie(Integer cesnanopie) {
        this.cesnanopie = cesnanopie;
    }

    public Integer getCesnanopie() {
        return cesnanopie;
    }

    public void setCesnanofla(Integer cesnanofla) {
        this.cesnanofla = cesnanofla;
    }

    public Integer getCesnanofla() {
        return cesnanofla;
    }

    public void setCesnconcli(Long cesnconcli) {
        this.cesnconcli = cesnconcli;
    }

    public Long getCesnconcli() {
        return cesnconcli;
    }


    public void setCescoligoz(String cescoligoz) {
        this.cescoligoz = cescoligoz;
    }

    public String getCescoligoz() {
        return cescoligoz;
    }

    public void setCescasteno(String cescasteno) {
        this.cescasteno = cescasteno;
    }

    public String getCescasteno() {
        return cescasteno;
    }

    public void setCescterato(String cescterato) {
        this.cescterato = cescterato;
    }

    public String getCescterato() {
        return cescterato;
    }

    public void setCescnormoz(String cescnormoz) {
        this.cescnormoz = cescnormoz;
    }

    public String getCescnormoz() {
        return cescnormoz;
    }
}
