package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

/**
 * CnplanfertId generated by hbm2java
 */

public class CnplanfertId implements java.io.Serializable {

	private Long cpflusuario;
	private Integer cpfnnumero;

	// Constructors

	/** default constructor */
	public CnplanfertId() {
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public Long getCpflusuario() {
		return this.cpflusuario;
	}

	public void setCpflusuario(Long cpflusuario) {
		this.cpflusuario = cpflusuario;
	}

	public Integer getCpfnnumero() {
		return this.cpfnnumero;
	}

	public void setCpfnnumero(Integer cpfnnumero) {
		this.cpfnnumero = cpfnnumero;
	}

	// no tiene llave compuesta.

}
