package org.profamilia.hc.model.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cnplanfert generated by hbm2java
 */

public class Cnplanfert implements java.io.Serializable {

	/**
	 * serialVersionUID class Cnplanfert
	 */
	private static final long serialVersionUID = 761154282710002686L;
	
	private CnplanfertId id;
	private Date cpfdfecpla;
	private Integer cpfntippla;
	private String cpfcmedico;
	private String cpfcinducc;
	private Date cpfddiahcg;
	private String cpfcestrad;
	private String cpfcesptip;
	private String cpfcpascat;
	private Integer cpfnespdon;
	private String cpfcgradie;
	private String cpfcovutip;
	private Integer cpfnovudon;
	private String cpfcgrabad;
	private Date cpfdfecgra;
	private Integer cpfnfolicu;
	private BigDecimal cpfaendome;
	private Integer cpfnfolovu;
	private Integer cpfnfolmad;
	private Integer cpfnfolfec;
	private Integer cpfndiacic;
	private Integer cpfndiagcf;
	private Integer cpfnestrad;
	private Integer cpfninducc;
	private Integer cpfnvolova;
	private Integer cpfnfolcen;
	private String cpfccancel;
	private Integer cpfnperiod;
	private Integer cpfnmes;
	private String cpfcmedic1;
	private String cpfcvalme1;
	private String cpfcmedic2;
	private String cpfcvalme2;
	private String cpfcmedic3;
	private String cpfcvalme3;
	private Integer cpfnclinic;
	private String cpfctipide;
	private Long cpfanumide;
	private String cpfcestado;
	private Integer cpfnnumint;
	private Integer version;
	private String cpfcbiotes;
	private String cpfcaspira;		
	private String cpfctipemb;
	private Integer cpfnpreend;
	private String cpfcidesp;
	private String cpfcidovu;
        private Long cpfnconcli;

	/**
	 * @return the version
	 */
	public final Integer getVersion() {
		return version;
	}

	/**
	 * @param version
	 *            the version to set
	 */
	public final void setVersion(Integer version) {
		this.version = version;
	}

	// Constructors

	/** default constructor */
	public Cnplanfert() {
            id = new CnplanfertId();
	}

	/** constructor with id */
	// HS == CnplanfertId
	public Cnplanfert(CnplanfertId id) {
		this.id = id;
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public CnplanfertId getId() {
        if(id == null){
            id = new CnplanfertId();
        }
        
		return this.id;
	}

	public void setId(CnplanfertId id) {
	    if(id == null){
	        id = new CnplanfertId();
	    }
		this.id = id;
	}

	public Date getCpfdfecpla() {
		return this.cpfdfecpla;
	}

	public void setCpfdfecpla(Date cpfdfecpla) {
		this.cpfdfecpla = cpfdfecpla;
	}

	public Integer getCpfntippla() {
		return this.cpfntippla;
	}

	public void setCpfntippla(Integer cpfntippla) {
		this.cpfntippla = cpfntippla;
	}

	public String getCpfcmedico() {
		return this.cpfcmedico;
	}

	public void setCpfcmedico(String cpfcmedico) {
		this.cpfcmedico = cpfcmedico;
	}

	public String getCpfcinducc() {
		return this.cpfcinducc;
	}

	public void setCpfcinducc(String cpfcinducc) {
		this.cpfcinducc = cpfcinducc;
	}

	public Date getCpfddiahcg() {
		return this.cpfddiahcg;
	}

	public void setCpfddiahcg(Date cpfddiahcg) {
		this.cpfddiahcg = cpfddiahcg;
	}

	public String getCpfcestrad() {
		return this.cpfcestrad;
	}

	public void setCpfcestrad(String cpfcestrad) {
		this.cpfcestrad = cpfcestrad;
	}

	public String getCpfcesptip() {
		return this.cpfcesptip;
	}

	public void setCpfcesptip(String cpfcesptip) {
		this.cpfcesptip = cpfcesptip;
	}

	public String getCpfcpascat() {
		return this.cpfcpascat;
	}

	public void setCpfcpascat(String cpfcpascat) {
		this.cpfcpascat = cpfcpascat;
	}

	public Integer getCpfnespdon() {
		return this.cpfnespdon;
	}

	public void setCpfnespdon(Integer cpfnespdon) {
		this.cpfnespdon = cpfnespdon;
	}

	public String getCpfcgradie() {
		return this.cpfcgradie;
	}

	public void setCpfcgradie(String cpfcgradie) {
		this.cpfcgradie = cpfcgradie;
	}

	public String getCpfcovutip() {
		return this.cpfcovutip;
	}

	public void setCpfcovutip(String cpfcovutip) {
		this.cpfcovutip = cpfcovutip;
	}

	public Integer getCpfnovudon() {
		return this.cpfnovudon;
	}

	public void setCpfnovudon(Integer cpfnovudon) {
		this.cpfnovudon = cpfnovudon;
	}

	public String getCpfcgrabad() {
		return this.cpfcgrabad;
	}

	public void setCpfcgrabad(String cpfcgrabad) {
		this.cpfcgrabad = cpfcgrabad;
	}

	public Date getCpfdfecgra() {
		return this.cpfdfecgra;
	}

	public void setCpfdfecgra(Date cpfdfecgra) {
		this.cpfdfecgra = cpfdfecgra;
	}

	public Integer getCpfnfolicu() {
		return this.cpfnfolicu;
	}

	public void setCpfnfolicu(Integer cpfnfolicu) {
		this.cpfnfolicu = cpfnfolicu;
	}

	public BigDecimal getCpfaendome() {
		return this.cpfaendome;
	}

	public void setCpfaendome(BigDecimal cpfaendome) {
		this.cpfaendome = cpfaendome;
	}

	public Integer getCpfnfolovu() {
		return this.cpfnfolovu;
	}

	public void setCpfnfolovu(Integer cpfnfolovu) {
		this.cpfnfolovu = cpfnfolovu;
	}

	public Integer getCpfnfolmad() {
		return this.cpfnfolmad;
	}

	public void setCpfnfolmad(Integer cpfnfolmad) {
		this.cpfnfolmad = cpfnfolmad;
	}

	public Integer getCpfnfolfec() {
		return this.cpfnfolfec;
	}

	public void setCpfnfolfec(Integer cpfnfolfec) {
		this.cpfnfolfec = cpfnfolfec;
	}

	public Integer getCpfndiacic() {
		return this.cpfndiacic;
	}

	public void setCpfndiacic(Integer cpfndiacic) {
		this.cpfndiacic = cpfndiacic;
	}

	public Integer getCpfndiagcf() {
		return this.cpfndiagcf;
	}

	public void setCpfndiagcf(Integer cpfndiagcf) {
		this.cpfndiagcf = cpfndiagcf;
	}

	public Integer getCpfnestrad() {
		return this.cpfnestrad;
	}

	public void setCpfnestrad(Integer cpfnestrad) {
		this.cpfnestrad = cpfnestrad;
	}

	public Integer getCpfninducc() {
		return this.cpfninducc;
	}

	public void setCpfninducc(Integer cpfninducc) {
		this.cpfninducc = cpfninducc;
	}

	public Integer getCpfnvolova() {
		return this.cpfnvolova;
	}

	public void setCpfnvolova(Integer cpfnvolova) {
		this.cpfnvolova = cpfnvolova;
	}

	public Integer getCpfnfolcen() {
		return this.cpfnfolcen;
	}

	public void setCpfnfolcen(Integer cpfnfolcen) {
		this.cpfnfolcen = cpfnfolcen;
	}

	public String getCpfccancel() {
		return this.cpfccancel;
	}

	public void setCpfccancel(String cpfccancel) {
		this.cpfccancel = cpfccancel;
	}

	public Integer getCpfnmes() {
		return this.cpfnmes;
	}

	public void setCpfnmes(Integer cpfnmes) {
		this.cpfnmes = cpfnmes;
	}

	public Integer getCpfnperiod() {
		return this.cpfnperiod;
	}

	public void setCpfnperiod(Integer cpfnperiod) {
		this.cpfnperiod = cpfnperiod;
	}

	public String getCpfcmedic1() {
		return cpfcmedic1;
	}

	public void setCpfcmedic1(String cpfcmedic1) {
		this.cpfcmedic1 = cpfcmedic1;
	}

	public String getCpfcvalme1() {
		return cpfcvalme1;
	}

	public void setCpfcvalme1(String cpfcvalme1) {
		this.cpfcvalme1 = cpfcvalme1;
	}

	public String getCpfcmedic2() {
		return cpfcmedic2;
	}

	public void setCpfcmedic2(String cpfcmedic2) {
		this.cpfcmedic2 = cpfcmedic2;
	}

	public String getCpfcvalme2() {
		return cpfcvalme2;
	}

	public void setCpfcvalme2(String cpfcvalme2) {
		this.cpfcvalme2 = cpfcvalme2;
	}

	public String getCpfcmedic3() {
		return cpfcmedic3;
	}

	public void setCpfcmedic3(String cpfcmedic3) {
		this.cpfcmedic3 = cpfcmedic3;
	}

	public String getCpfcvalme3() {
		return cpfcvalme3;
	}

	public void setCpfcvalme3(String cpfcvalme3) {
		this.cpfcvalme3 = cpfcvalme3;
	}

	public Integer getCpfnclinic() {
		return cpfnclinic;
	}

	public void setCpfnclinic(Integer cpfnclinic) {
		this.cpfnclinic = cpfnclinic;
	}

	public String getCpfctipide() {
		return cpfctipide;
	}

	public void setCpfctipide(String cpfctipide) {
		this.cpfctipide = cpfctipide;
	}

	public Long getCpfanumide() {
		return cpfanumide;
	}

	public void setCpfanumide(Long cpfanumide) {
		this.cpfanumide = cpfanumide;
	}

	public Long getCpflusuario() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCpflusuario();
	}

	public void setCpflusuario(Long cpflusuario) {
		if (this.id == null) {
			this.id = new CnplanfertId();
		}
		this.id.setCpflusuario(cpflusuario);
	}

	public Integer getCpfnnumero() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCpfnnumero();
	}

	public void setCpfnnumero(Integer cpfnnumero) {
		if (this.id == null) {
			this.id = new CnplanfertId();
		}
		this.id.setCpfnnumero(cpfnnumero);
	}

	public String getCpfcestado() {
		return cpfcestado;
	}

	public void setCpfcestado(String cpfcestado) {
		this.cpfcestado = cpfcestado;
	}

	public Integer getCpfnnumint() {
		return cpfnnumint;
	}

	public void setCpfnnumint(Integer cpfnnumint) {
		this.cpfnnumint = cpfnnumint;
	}

	public String getCpfcbiotes() {
		return cpfcbiotes;
	}

	public void setCpfcbiotes(String cpfcbiotes) {
		this.cpfcbiotes = cpfcbiotes;
	}

	public String getCpfcaspira() {
		return cpfcaspira;
	}

	public void setCpfcaspira(String cpfcaspira) {
		this.cpfcaspira = cpfcaspira;
	}

	public String getCpfcidesp() {
		return cpfcidesp;
	}

	public void setCpfcidesp(String cpfcidesp) {
		this.cpfcidesp = cpfcidesp;
	}

	public String getCpfcidovu() {
		return cpfcidovu;
	}

	public void setCpfcidovu(String cpfcidovu) {
		this.cpfcidovu = cpfcidovu;
	}

	public String getCpfctipemb() {
		return cpfctipemb;
	}

	public void setCpfctipemb(String cpfctipemb) {
		this.cpfctipemb = cpfctipemb;
	}

	public Integer getCpfnpreend() {
		return cpfnpreend;
	}

	public void setCpfnpreend(Integer cpfnpreend) {
		this.cpfnpreend = cpfnpreend;
	}

    public void setCpfnconcli(Long cpfnconcli) {
        this.cpfnconcli = cpfnconcli;
    }

    public Long getCpfnconcli() {
        return cpfnconcli;
    }
}
