package org.profamilia.hc.model.dto;

import java.math.BigDecimal;


/**
 * CnprofxconId generated by hbm2java
 */
public class CnprofxconId implements java.io.Serializable {


    private BigDecimal cpnnprofes;
    private Integer cpnnconcli;


    // Constructors

    /** default constructor */
    public CnprofxconId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public BigDecimal getCpnnprofes() {
        return this.cpnnprofes;
    }

    public void setCpnnprofes(BigDecimal cpnnprofes) {
        this.cpnnprofes = cpnnprofes;
    }


    public Integer getCpnnconcli() {
        return this.cpnnconcli;
    }

    public void setCpnnconcli(Integer cpnnconcli) {
        this.cpnnconcli = cpnnconcli;
    }


    // no tiene llave compuesta.


}
