package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cpclinica generated by hbm2java
 */
public class Cpclinica implements java.io.Serializable {


    private Integer cclncodigo;
    private String cclcnombre;
    private String cclcdirect;
    private String cclcdirecc;
    private String cclctelefo;
    private Date ccldfecreg;
    private String cclcusuar;
    private String cclcciudad;
    private String cclccodsgs;
    private String cclcestado;
    private String cclcimputa;
    private String cclcfarmac;
    private String cclccorreo;
    private String cclcfax;
    private String cclccoradm;
    private Integer cclnregion;
    private String cclccorreg;
    private String cclccodippf;
    private String cclcippfmov;
    private String cclncoddane;
    private Integer version;


    // no tiene llave compuesta.


    public void setCclncodigo(Integer cclncodigo) {
        this.cclncodigo = cclncodigo;
    }

    public Integer getCclncodigo() {
        return cclncodigo;
    }

    public void setCclcnombre(String cclcnombre) {
        this.cclcnombre = cclcnombre;
    }

    public String getCclcnombre() {
        return cclcnombre;
    }

    public void setCclcdirect(String cclcdirect) {
        this.cclcdirect = cclcdirect;
    }

    public String getCclcdirect() {
        return cclcdirect;
    }

    public void setCclcdirecc(String cclcdirecc) {
        this.cclcdirecc = cclcdirecc;
    }

    public String getCclcdirecc() {
        return cclcdirecc;
    }

    public void setCclctelefo(String cclctelefo) {
        this.cclctelefo = cclctelefo;
    }

    public String getCclctelefo() {
        return cclctelefo;
    }

    public void setCcldfecreg(Date ccldfecreg) {
        this.ccldfecreg = ccldfecreg;
    }

    public Date getCcldfecreg() {
        return ccldfecreg;
    }

    public void setCclcusuar(String cclcusuar) {
        this.cclcusuar = cclcusuar;
    }

    public String getCclcusuar() {
        return cclcusuar;
    }

    public void setCclcciudad(String cclcciudad) {
        this.cclcciudad = cclcciudad;
    }

    public String getCclcciudad() {
        return cclcciudad;
    }

    public void setCclccodsgs(String cclccodsgs) {
        this.cclccodsgs = cclccodsgs;
    }

    public String getCclccodsgs() {
        return cclccodsgs;
    }

    public void setCclcestado(String cclcestado) {
        this.cclcestado = cclcestado;
    }

    public String getCclcestado() {
        return cclcestado;
    }

    public void setCclcimputa(String cclcimputa) {
        this.cclcimputa = cclcimputa;
    }

    public String getCclcimputa() {
        return cclcimputa;
    }

    public void setCclcfarmac(String cclcfarmac) {
        this.cclcfarmac = cclcfarmac;
    }

    public String getCclcfarmac() {
        return cclcfarmac;
    }

    public void setCclccorreo(String cclccorreo) {
        this.cclccorreo = cclccorreo;
    }

    public String getCclccorreo() {
        return cclccorreo;
    }

    public void setCclcfax(String cclcfax) {
        this.cclcfax = cclcfax;
    }

    public String getCclcfax() {
        return cclcfax;
    }

    public void setCclccoradm(String cclccoradm) {
        this.cclccoradm = cclccoradm;
    }

    public String getCclccoradm() {
        return cclccoradm;
    }

    public void setCclnregion(Integer cclnregion) {
        this.cclnregion = cclnregion;
    }

    public Integer getCclnregion() {
        return cclnregion;
    }

    public void setCclccorreg(String cclccorreg) {
        this.cclccorreg = cclccorreg;
    }

    public String getCclccorreg() {
        return cclccorreg;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getVersion() {
        return version;
    }

    public void setCclccodippf(String cclccodippf) {
        this.cclccodippf = cclccodippf;
    }

    public String getCclccodippf() {
        return cclccodippf;
    }

    public void setCclcippfmov(String cclcippfmov) {
        this.cclcippfmov = cclcippfmov;
    }

    public String getCclcippfmov() {
        return cclcippfmov;
    }

    public void setCclncoddane(String cclncoddane) {
        this.cclncoddane = cclncoddane;
    }

    public String getCclncoddane() {
        return cclncoddane;
    }
}
