package org.profamilia.hc.model.dto;


/**
 * Cpconsec generated by hbm2java
 */
public class Cpconsec implements java.io.Serializable {


    private Integer conncodigo;
    private String concdescri;
    private Integer connnumero;


    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }


    // Constructors

    /** default constructor */
    public Cpconsec() {
    }

    /** constructor with id */
    public
    // HS == short


    Cpconsec(Integer conncodigo) {
        this.conncodigo = conncodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getConncodigo() {
        return this.conncodigo;
    }

    public void setConncodigo(Integer conncodigo) {
        this.conncodigo = conncodigo;
    }


    public String getConcdescri() {
        return this.concdescri;
    }

    public void setConcdescri(String concdescri) {
        this.concdescri = concdescri;
    }


    public Integer getConnnumero() {
        return this.connnumero;
    }

    public void setConnnumero(Integer connnumero) {
        this.connnumero = connnumero;
    }


    // no tiene llave compuesta.


}
