package org.profamilia.hc.model.dto;


/**
 * CpcontratoId generated by hbm2java
 */
public class CpcontratoId implements java.io.Serializable {


    private Integer ccnnclinic;
    private Integer ccnnnumero;


    // Constructors

    /** default constructor */
    public CpcontratoId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    /**
     * @return
     */
    public Integer getCcnnclinic() {
        return this.ccnnclinic;
    }

    /**
     * @param ccnnclinic
     */
    public void setCcnnclinic(Integer ccnnclinic) {
        this.ccnnclinic = ccnnclinic;
    }


    /**
     * @return
     */
    public Integer getCcnnnumero() {
        return this.ccnnnumero;
    }

    /**
     * @param ccnnnumero
     */
    public void setCcnnnumero(Integer ccnnnumero) {
        this.ccnnnumero = ccnnnumero;
    }


    // no tiene llave compuesta.


}
