package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;

/**
 * Cpdonante generated by hbm2java
 */

public class Cpdonante implements java.io.Serializable {

	private BigDecimal cdnncodigo;
	private String cdncdescri;
	private String cdncestado;
	private Date cdndfecreg;
	private String cdncusureg;
	private String cdncproyec;
	private String cdncexeiva;

	private Integer version;

	/**
	 * @return the version
	 */
	public final Integer getVersion() {
		return version;
	}

	/**
	 * @param version
	 *            the version to set
	 */
	public final void setVersion(Integer version) {
		this.version = version;
	}

	// Constructors

	/** default constructor */
	public Cpdonante() {
	}

	/** constructor with id */
	// HS == short

	public Cpdonante(BigDecimal cdnncodigo) {
		this.cdnncodigo = cdnncodigo;
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public BigDecimal getCdnncodigo() {
		return this.cdnncodigo;
	}

	public void setCdnncodigo(BigDecimal cdnncodigo) {
		this.cdnncodigo = cdnncodigo;
	}

	public String getCdncdescri() {
		return this.cdncdescri;
	}

	public void setCdncdescri(String cdncdescri) {
		this.cdncdescri = cdncdescri;
	}

	public String getCdncestado() {
		return this.cdncestado;
	}

	public void setCdncestado(String cdncestado) {
		this.cdncestado = cdncestado;
	}

	public Date getCdndfecreg() {
		return this.cdndfecreg;
	}

	public void setCdndfecreg(Date cdndfecreg) {
		this.cdndfecreg = cdndfecreg;
	}

	public String getCdncusureg() {
		return this.cdncusureg;
	}

	public void setCdncusureg(String cdncusureg) {
		this.cdncusureg = cdncusureg;
	}

	public String getCdncproyec() {
		return this.cdncproyec;
	}

	public void setCdncproyec(String cdncproyec) {
		this.cdncproyec = cdncproyec;
	}

	public String getCdncexeiva() {
		return cdncexeiva;
	}

	public void setCdncexeiva(String cdncexeiva) {
		this.cdncexeiva = cdncexeiva;
	}
	
	// no tiene llave compuesta.

}
