package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cpentidadadm generated by hbm2java
 */
public class Cpentidadadm implements java.io.Serializable {

    private String ceaccodigo;
    private String ceacnombre;
    private Date ceadfecregistr;
    private String ceacoperador;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cpentidadadm() {
    }

    /** constructor with id */
    public
    // HS == short


    Cpentidadadm(String ceaccodigo) {
        this.ceaccodigo = ceaccodigo;
    }

    public String getCeaccodigo() {
        return ceaccodigo;
    }

    public void setCeaccodigo(String ceaccodigo) {
        this.ceaccodigo = ceaccodigo;
    }

    public String getCeacnombre() {
        return ceacnombre;
    }

    public void setCeacnombre(String ceacnombre) {
        this.ceacnombre = ceacnombre;
    }

    public Date getCeadfecregistr() {
        return ceadfecregistr;
    }

    public void setCeadfecregistr(Date ceadfecregistr) {
        this.ceadfecregistr = ceadfecregistr;
    }

    public String getCeacoperador() {
        return ceacoperador;
    }

    public void setCeacoperador(String ceacoperador) {
        this.ceacoperador = ceacoperador;
    }


    // Property accessors


    // no tiene llave compuesta.

}
