package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Cppaquserv generated by hbm2java
 */
public class Cppaquserv implements java.io.Serializable {

    private CppaquservId id;
    private Date cpedfecreg;
    private String cpecusuari;
    private BigDecimal cpeaporiva;
    private Integer cpendiafle;
    private String cpecinsser;
    private String cpecserpri;
    private Integer version;
    private String cpecestado;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cppaquserv() {
    }

    /** constructor with id */
    public
    // HS == CppaquservId


    Cppaquserv(CppaquservId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public void setId(CppaquservId id) {
        this.id = id;
    }

    public CppaquservId getId() {
        return id;
    }

    public void setCpedfecreg(Date cpedfecreg) {
        this.cpedfecreg = cpedfecreg;
    }

    public Date getCpedfecreg() {
        return cpedfecreg;
    }

    public void setCpecusuari(String cpecusuari) {
        this.cpecusuari = cpecusuari;
    }

    public String getCpecusuari() {
        return cpecusuari;
    }

    public void setCpeaporiva(BigDecimal cpeaporiva) {
        this.cpeaporiva = cpeaporiva;
    }

    public BigDecimal getCpeaporiva() {
        return cpeaporiva;
    }

    public void setCpendiafle(Integer cpendiafle) {
        this.cpendiafle = cpendiafle;
    }

    public Integer getCpendiafle() {
        return cpendiafle;
    }

    public void setCpecinsser(String cpecinsser) {
        this.cpecinsser = cpecinsser;
    }

    public String getCpecinsser() {
        return cpecinsser;
    }

    public void setCpecserpri(String cpecserpri) {
        this.cpecserpri = cpecserpri;
    }

    public String getCpecserpri() {
        return cpecserpri;
    }


    public void setCpecestado(String cpecestado) {
        this.cpecestado = cpecestado;
    }

    public String getCpecestado() {
        return cpecestado;
    }
}
