package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cppais generated by hbm2java
 */
public class

Cppais implements java.io.Serializable {


    private Integer cpancodigo;
    private String cpacnombre;
    private String cpacodalfa2;
    private String cpacodalfa3; 

    // Constructors

    /** default constructor */
    public Cppais() {
    }

    /** constructor with id */
    public
    // HS == short


    Cppais(Integer cpancodigo) {
        this.cpancodigo = cpancodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public void setCpancodigo(Integer cpancodigo) {
        this.cpancodigo = cpancodigo;
    }

    public Integer getCpancodigo() {
        return cpancodigo;
    }

    public void setCpacnombre(String cpacnombre) {
        this.cpacnombre = cpacnombre;
    }

    public String getCpacnombre() {
        return cpacnombre;
    }

    public void setCpacodalfa2(String cpacodalfa2) {
        this.cpacodalfa2 = cpacodalfa2;
    }

    public String getCpacodalfa2() {
        return cpacodalfa2;
    }

    public void setCpacodalfa3(String cpacodalfa3) {
        this.cpacodalfa3 = cpacodalfa3;
    }

    public String getCpacodalfa3() {
        return cpacodalfa3;
    }
}
