package org.profamilia.hc.model.dto;


/**
 * CppaquservId generated by hbm2java
 */
public class CppaquservId implements java.io.Serializable {

    private String cpecpaquet;
    private String cpecservic;
    private Integer cpendiaate;


    // Constructors

    /** default constructor */
    public CppaquservId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors





    // no tiene llave compuesta.


    public void setCpecpaquet(String cpecpaquet) {
        this.cpecpaquet = cpecpaquet;
    }

    public String getCpecpaquet() {
        return cpecpaquet;
    }

    public void setCpecservic(String cpecservic) {
        this.cpecservic = cpecservic;
    }

    public String getCpecservic() {
        return cpecservic;
    }

    public void setCpendiaate(Integer cpendiaate) {
        this.cpendiaate = cpendiaate;
    }

    public Integer getCpendiaate() {
        return cpendiaate;
    }
}
