package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Cpprofesio generated by hbm2java
 */
public class

Cpprofesio implements java.io.Serializable {


    private CpprofesioId id;
    private String cpfcnombre;
    private BigDecimal cpfacedula;
    private String cpfcdirecc;
    private String cpfctelefo;
    private Integer cpfntipcon;
    private Integer cpfncuomes;
    private Integer cpfncuosem;
    private Integer cpfncuodia;
    private Integer cpfncuolun;
    private Integer cpfncuomar;
    private Integer cpfncuomie;
    private Integer cpfncuojue;
    private Integer cpfncuovie;
    private Integer cpfncuosab;
    private String cpfcobliga;
    private Integer cpfntippro;
    private Date cpfdfecreg;
    private Date cpfthorreg;
    private String cpfcusuar;
    private String cpfcestado;
    private String cpfctipper;
    private BigDecimal cpfaporfte;
    private BigDecimal cpfaporica;
    private BigDecimal cpfaportim;
    private Integer cpfnauxcnt;
    private Integer cpfncodimp;
    private BigDecimal cpfacotarp;
    private BigDecimal cpfapagtim;
    private BigDecimal cpffporarp;
    private Integer cpfntipoespe;
    private String cpfctipide;
    

    /** nullable persistent field */
    private String cpfcregmedic;

    private Integer version;
    
    private Integer numeroSala;
    
    private String nombreResidente;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cpprofesio() {
    }

    /** constructor with id */
    public
    // HS == CpprofesioId


    Cpprofesio(CpprofesioId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CpprofesioId getId() {
        return this.id;
    }

    public void setId(CpprofesioId id) {
        this.id = id;
    }


    public String getCpfcnombre() {
        return this.cpfcnombre;
    }

    public void setCpfcnombre(String cpfcnombre) {
        this.cpfcnombre = cpfcnombre;
    }


    public BigDecimal getCpfacedula() {
        return this.cpfacedula;
    }

    public void setCpfacedula(BigDecimal cpfacedula) {
        this.cpfacedula = cpfacedula;
    }


    public String getCpfcdirecc() {
        return this.cpfcdirecc;
    }

    public void setCpfcdirecc(String cpfcdirecc) {
        this.cpfcdirecc = cpfcdirecc;
    }


    public String getCpfctelefo() {
        return this.cpfctelefo;
    }

    public void setCpfctelefo(String cpfctelefo) {
        this.cpfctelefo = cpfctelefo;
    }


    public Integer getCpfntipcon() {
        return this.cpfntipcon;
    }

    public void setCpfntipcon(Integer cpfntipcon) {
        this.cpfntipcon = cpfntipcon;
    }


    public Integer getCpfncuomes() {
        return this.cpfncuomes;
    }

    public void setCpfncuomes(Integer cpfncuomes) {
        this.cpfncuomes = cpfncuomes;
    }


    public Integer getCpfncuosem() {
        return this.cpfncuosem;
    }

    public void setCpfncuosem(Integer cpfncuosem) {
        this.cpfncuosem = cpfncuosem;
    }


    public Integer getCpfncuodia() {
        return this.cpfncuodia;
    }

    public void setCpfncuodia(Integer cpfncuodia) {
        this.cpfncuodia = cpfncuodia;
    }


    public Integer getCpfncuolun() {
        return this.cpfncuolun;
    }

    public void setCpfncuolun(Integer cpfncuolun) {
        this.cpfncuolun = cpfncuolun;
    }


    public Integer getCpfncuomar() {
        return this.cpfncuomar;
    }

    public void setCpfncuomar(Integer cpfncuomar) {
        this.cpfncuomar = cpfncuomar;
    }


    public Integer getCpfncuomie() {
        return this.cpfncuomie;
    }

    public void setCpfncuomie(Integer cpfncuomie) {
        this.cpfncuomie = cpfncuomie;
    }


    public Integer getCpfncuojue() {
        return this.cpfncuojue;
    }

    public void setCpfncuojue(Integer cpfncuojue) {
        this.cpfncuojue = cpfncuojue;
    }


    public Integer getCpfncuovie() {
        return this.cpfncuovie;
    }

    public void setCpfncuovie(Integer cpfncuovie) {
        this.cpfncuovie = cpfncuovie;
    }


    public Integer getCpfncuosab() {
        return this.cpfncuosab;
    }

    public void setCpfncuosab(Integer cpfncuosab) {
        this.cpfncuosab = cpfncuosab;
    }


    public String getCpfcobliga() {
        return this.cpfcobliga;
    }

    public void setCpfcobliga(String cpfcobliga) {
        this.cpfcobliga = cpfcobliga;
    }


    public Integer getCpfntippro() {
        return this.cpfntippro;
    }

    public void setCpfntippro(Integer cpfntippro) {
        this.cpfntippro = cpfntippro;
    }


    public Date getCpfdfecreg() {
        return this.cpfdfecreg;
    }

    public void setCpfdfecreg(Date cpfdfecreg) {
        this.cpfdfecreg = cpfdfecreg;
    }


    public Date getCpfthorreg() {
        return this.cpfthorreg;
    }

    public void setCpfthorreg(Date cpfthorreg) {
        this.cpfthorreg = cpfthorreg;
    }


    public String getCpfcusuar() {
        return this.cpfcusuar;
    }

    public void setCpfcusuar(String cpfcusuar) {
        this.cpfcusuar = cpfcusuar;
    }


    public String getCpfcestado() {
        return this.cpfcestado;
    }

    public void setCpfcestado(String cpfcestado) {
        this.cpfcestado = cpfcestado;
    }


    public String getCpfctipper() {
        return this.cpfctipper;
    }

    public void setCpfctipper(String cpfctipper) {
        this.cpfctipper = cpfctipper;
    }


    public BigDecimal getCpfaporfte() {
        return this.cpfaporfte;
    }

    public void setCpfaporfte(BigDecimal cpfaporfte) {
        this.cpfaporfte = cpfaporfte;
    }


    public BigDecimal getCpfaporica() {
        return this.cpfaporica;
    }

    public void setCpfaporica(BigDecimal cpfaporica) {
        this.cpfaporica = cpfaporica;
    }


    public BigDecimal getCpfaportim() {
        return this.cpfaportim;
    }

    public void setCpfaportim(BigDecimal cpfaportim) {
        this.cpfaportim = cpfaportim;
    }


    public Integer getCpfnauxcnt() {
        return this.cpfnauxcnt;
    }

    public void setCpfnauxcnt(Integer cpfnauxcnt) {
        this.cpfnauxcnt = cpfnauxcnt;
    }


    public Integer getCpfncodimp() {
        return this.cpfncodimp;
    }

    public void setCpfncodimp(Integer cpfncodimp) {
        this.cpfncodimp = cpfncodimp;
    }


    public BigDecimal getCpfacotarp() {
        return this.cpfacotarp;
    }

    public void setCpfacotarp(BigDecimal cpfacotarp) {
        this.cpfacotarp = cpfacotarp;
    }

    public BigDecimal getCpfapagtim() {
        return cpfapagtim;
    }

    public void setCpfapagtim(BigDecimal cpfapagtim) {
        this.cpfapagtim = cpfapagtim;
    }

    public BigDecimal getCpffporarp() {
        return cpffporarp;
    }

    public void setCpffporarp(BigDecimal cpffporarp) {
        this.cpffporarp = cpffporarp;
    }


    public BigDecimal getCpfncodigo() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCpfncodigo();
    }

    public void setCpfncodigo(BigDecimal cpfncodigo) {
        if (this.id == null) {
            this.id = new CpprofesioId();
        }
        this.id.setCpfncodigo(cpfncodigo);
    }

    public Integer getCpfnclinic() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCpfnclinic();
    }

    public void setCpfnclinic(Integer cpfnclinic) {
        if (this.id == null) {
            this.id = new CpprofesioId();
        }
        this.id.setCpfnclinic(cpfnclinic);
    }


    public void setCpfcregmedic(String cpfcregmedic) {
        this.cpfcregmedic = cpfcregmedic;
    }

    public String getCpfcregmedic() {
        return cpfcregmedic;
    }

    public void setCpfntipoespe(Integer cpfntipoespe) {
        this.cpfntipoespe = cpfntipoespe;
    }

    public Integer getCpfntipoespe() {
        return cpfntipoespe;
    }

    public void setNumeroSala(Integer numeroSala) {
        this.numeroSala = numeroSala;
    }

    public Integer getNumeroSala() {
        return numeroSala;
    }

    public void setNombreResidente(String nombreResidente) {
        this.nombreResidente = nombreResidente;
    }

    public String getNombreResidente() {
        return nombreResidente;
    }

    public void setCpfctipide(String cpfctipide) {
        this.cpfctipide = cpfctipide;
    }

    public String getCpfctipide() {
        return cpfctipide;
    }
}
