package org.profamilia.hc.model.dto;

import java.math.BigDecimal;


/**
 * CpprofesioId generated by hbm2java
 */
public class

CpprofesioId implements java.io.Serializable {


    private BigDecimal cpfncodigo;
    private Integer cpfnclinic;


    // Constructors

    /** default constructor */
    public CpprofesioId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public BigDecimal getCpfncodigo() {
        return this.cpfncodigo;
    }

    public void setCpfncodigo(BigDecimal cpfncodigo) {
        this.cpfncodigo = cpfncodigo;
    }


    public Integer getCpfnclinic() {
        return this.cpfnclinic;
    }

    public void setCpfnclinic(Integer cpfnclinic) {
        this.cpfnclinic = cpfnclinic;
    }


    // no tiene llave compuesta.


}
