package org.profamilia.hc.model.dto;
import java.util.Date;

/**
 * Cprestxcon generated by hbm2java
 */

public class Cprestxcon implements java.io.Serializable {

	private CprestxconId id;
	private String crxcservic;
	private Integer crxnedamin;
	private Integer crxnedamax;
	private String crxcsexo;
	private Date crxdfecreg;
	private String crxcusuari;
	private String crxcestado;
	private String crxcregime;
	private Integer crxndiafac;
	private String crxctideex;

	private Integer version;

	/**
	 * @return the version
	 */
	public final Integer getVersion() {
		return version;
	}

	/**
	 * @param version
	 *            the version to set
	 */
	public final void setVersion(Integer version) {
		this.version = version;
	}

	// Constructors

	/** default constructor */
	public Cprestxcon() {
	}

	/** constructor with id */
	// HS == CprestxconId

	public Cprestxcon(CprestxconId id) {
		this.id = id;
	}

	// HS SEPARADOR CONSTRUCTOR

	// Property accessors

	public CprestxconId getId() {
		return this.id;
	}

	public void setId(CprestxconId id) {
		this.id = id;
	}

	public String getCrxcservic() {
		return this.crxcservic;
	}

	public void setCrxcservic(String crxcservic) {
		this.crxcservic = crxcservic;
	}

	public Integer getCrxnedamin() {
		return this.crxnedamin;
	}

	public void setCrxnedamin(Integer crxnedamin) {
		this.crxnedamin = crxnedamin;
	}

	public Integer getCrxnedamax() {
		return this.crxnedamax;
	}

	public void setCrxnedamax(Integer crxnedamax) {
		this.crxnedamax = crxnedamax;
	}

	public String getCrxcsexo() {
		return this.crxcsexo;
	}

	public void setCrxcsexo(String crxcsexo) {
		this.crxcsexo = crxcsexo;
	}

	public Date getCrxdfecreg() {
		return this.crxdfecreg;
	}

	public void setCrxdfecreg(Date crxdfecreg) {
		this.crxdfecreg = crxdfecreg;
	}

	public String getCrxcusuari() {
		return this.crxcusuari;
	}

	public void setCrxcusuari(String crxcusuari) {
		this.crxcusuari = crxcusuari;
	}

	public String getCrxcestado() {
		return this.crxcestado;
	}

	public void setCrxcestado(String crxcestado) {
		this.crxcestado = crxcestado;
	}

	public String getCrxcregime() {
		return this.crxcregime;
	}

	public void setCrxcregime(String crxcregime) {
		this.crxcregime = crxcregime;
	}

	public String getCrxctideex() {
		return this.crxctideex;
	}

	public void setCrxctideex(String crxctideex) {
		this.crxctideex = crxctideex;
	}

	public Integer getCrxndiafac() {
		return crxndiafac;
	}

	public void setCrxndiafac(Integer crxndiafac) {
		this.crxndiafac = crxndiafac;
	}

	public Integer getCrxnclinic() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCrxnclinic();
	}

	public void setCrxnclinic(Integer crxnclinic) {
		if (this.id == null) {
			this.id = new CprestxconId();
		}
		this.id.setCrxnclinic(crxnclinic);
	}

	public Integer getCrxncontra() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCrxncontra();
	}

	public void setCrxncontra(Integer crxncontra) {
		if (this.id == null) {
			this.id = new CprestxconId();
		}
		this.id.setCrxncontra(crxncontra);
	}

	public Integer getCrxnconsec() {
		if (this.id == null) {
			return null;
		}
		return this.id.getCrxnconsec();
	}

	public void setCrxnconsec(Integer crxnconsec) {
		if (this.id == null) {
			this.id = new CprestxconId();
		}
		this.id.setCrxnconsec(crxnconsec);
	}

}
