package org.profamilia.hc.model.dto;



/**
 * CprestxconId generated by hbm2java
 */

public class CprestxconId  implements java.io.Serializable {



    private Integer crxnclinic;
    private Integer crxncontra;
    private Integer crxnconsec;


    // Constructors

    /** default constructor */
    public CprestxconId() {
    }
    

// HS SEPARADOR CONSTRUCTOR

    

   
    // Property accessors


    public Integer getCrxnclinic() {
        return this.crxnclinic;
    }
    
    public void setCrxnclinic(
						Integer crxnclinic) {
        this.crxnclinic = crxnclinic;
    }


    public Integer getCrxncontra() {
        return this.crxncontra;
    }
    
    public void setCrxncontra(
						Integer crxncontra) {
        this.crxncontra = crxncontra;
    }


    public Integer getCrxnconsec() {
        return this.crxnconsec;
    }
    
    public void setCrxnconsec(
						Integer crxnconsec) {
        this.crxnconsec = crxnconsec;
    }
   








	// no tiene llave compuesta.


}
