package org.profamilia.hc.model.dto;


/**
 * CpsalaespeId generated by hbm2java
 */
public class

CpsalaespeId implements java.io.Serializable {


    private Integer cslnclinic;
    private Integer cslnnumero;


    // Constructors

    /** default constructor */
    public CpsalaespeId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCslnclinic() {
        return this.cslnclinic;
    }

    public void setCslnclinic(Integer cslnclinic) {
        this.cslnclinic = cslnclinic;
    }


    public Integer getCslnnumero() {
        return this.cslnnumero;
    }

    public void setCslnnumero(Integer cslnnumero) {
        this.cslnnumero = cslnnumero;
    }


    // no tiene llave compuesta.


}
