package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;

import org.profamilia.hc.view.constantes.IConstantes;


/**
 * Cpservicio generated by hbm2java
 */
public class

Cpservicio implements java.io.Serializable {


    private String csvccodigo;
    private Integer csvngrupo;
    private Integer csvnsubgru;
    private String csvcnombre;
    private Date csvdfeccre;
    private Date csvdfecmod;
    private BigDecimal csvavalser;
    private BigDecimal csvamincon;
    private BigDecimal csvaporiva;
    private String csvcswvalo;
    private Integer csvnswtipo;
    private String csvcctadeb;
    private String csvcctacre;
    private String csvccencos;
    private String csvcusuar;
    private String csvcestado;
    private Integer csvncodinv;
    private Integer csvntipcon;
    private String csvccups;
    private String csvcswpaqu;
    private String csvcsollot;
    private Integer csvnedamin;
    private Integer csvnedamax;
    private String csvcsexo;
    private Integer csvntiphis;
    private String csvccodcups;
    private String csvcrelecost;
    private String csvctipomat;
    private String csvcareauso;
    // Se utilizan para el buscador de cirugias
    private String csvcopera1;
    private String csvcopera2;
    private String csvcnombre2;
    private String csvcnombre3;
    private Integer csvntipage;
    private Integer version;
    private String wtipcito;
    private String csvcteleorie;

    // Esta Variable no es de la Base de Datos, es una variable que me permite asignarle 
    // Servicios a un profesional

    private String cirujanoSelect;
    
    private String nombreServicios;
    
    //Se agrega el campo a fin de poder transitar la observaci�n, hcadfecreg a Control Adicional, 
    //este campo no est� en la tabla correspondiente de la DB
    private String observaciones;
    private boolean agregado;
    private Date fechaAgregado;
    private String operadorAgregado;
    private Integer clinicaAgregado;
    private String tipoServicioAgregado;
    private String csvcaplicons;
    private Integer csvcpruerapi;
    
    //Se utilizan estas variables para el acumulador de costos
  

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cpservicio() {
    }


    /**
     * @param csvccodigo
     */
    public void setCsvccodigo(String csvccodigo) {
        this.csvccodigo = csvccodigo;
    }

    /**
     * @return
     */
    public String getCsvccodigo() {
   
        return csvccodigo;
    }

    /**
     * @param csvngrupo
     */
    public void setCsvngrupo(Integer csvngrupo) {
        this.csvngrupo = csvngrupo;
    }

    /**
     * @return
     */
    public Integer getCsvngrupo() {
        return csvngrupo;
    }

    /**
     * @param csvnsubgru
     */
    public void setCsvnsubgru(Integer csvnsubgru) {
        this.csvnsubgru = csvnsubgru;
    }

    /**
     * @return
     */
    public Integer getCsvnsubgru() {
        return csvnsubgru;
    }

    /**
     * @param csvcnombre
     */
    public void setCsvcnombre(String csvcnombre) {
        this.csvcnombre = csvcnombre;
    }

    /**
     * @return
     */
    public String getCsvcnombre() {
        return csvcnombre;
    }

    /**
     * @param csvdfeccre
     */
    public void setCsvdfeccre(Date csvdfeccre) {
        this.csvdfeccre = csvdfeccre;
    }

    /**
     * @return
     */
    public Date getCsvdfeccre() {
        return csvdfeccre;
    }

    /**
     * @param csvdfecmod
     */
    public void setCsvdfecmod(Date csvdfecmod) {
        this.csvdfecmod = csvdfecmod;
    }

    /**
     * @return
     */
    public Date getCsvdfecmod() {
        return csvdfecmod;
    }

    /**
     * @param csvavalser
     */
    public void setCsvavalser(BigDecimal csvavalser) {
        this.csvavalser = csvavalser;
    }

    /**
     * @return
     */
    public BigDecimal getCsvavalser() {
        return csvavalser;
    }

    /**
     * @param csvamincon
     */
    public void setCsvamincon(BigDecimal csvamincon) {
        this.csvamincon = csvamincon;
    }

    /**
     * @return
     */
    public BigDecimal getCsvamincon() {
        return csvamincon;
    }

    /**
     * @param csvaporiva
     */
    public void setCsvaporiva(BigDecimal csvaporiva) {
        this.csvaporiva = csvaporiva;
    }

    /**
     * @return
     */
    public BigDecimal getCsvaporiva() {
        return csvaporiva;
    }

    /**
     * @param csvcswvalo
     */
    public void setCsvcswvalo(String csvcswvalo) {
        this.csvcswvalo = csvcswvalo;
    }

    /**
     * @return
     */
    public String getCsvcswvalo() {
        return csvcswvalo;
    }

    /**
     * @param csvnswtipo
     */
    public void setCsvnswtipo(Integer csvnswtipo) {
        this.csvnswtipo = csvnswtipo;
    }

    /**
     * @return
     */
    public Integer getCsvnswtipo() {
        return csvnswtipo;
    }

    /**
     * @param csvcctadeb
     */
    public void setCsvcctadeb(String csvcctadeb) {
        this.csvcctadeb = csvcctadeb;
    }

    /**
     * @return
     */
    public String getCsvcctadeb() {
        return csvcctadeb;
    }

    /**
     * @param csvcctacre
     */
    public void setCsvcctacre(String csvcctacre) {
        this.csvcctacre = csvcctacre;
    }

    /**
     * @return
     */
    public String getCsvcctacre() {
        return csvcctacre;
    }

    /**
     * @param csvccencos
     */
    public void setCsvccencos(String csvccencos) {
        this.csvccencos = csvccencos;
    }

    /**
     * @return
     */
    public String getCsvccencos() {
        return csvccencos;
    }

    /**
     * @param csvcusuar
     */
    public void setCsvcusuar(String csvcusuar) {
        this.csvcusuar = csvcusuar;
    }

    /**
     * @return
     */
    public String getCsvcusuar() {
        return csvcusuar;
    }

    /**
     * @param csvcestado
     */
    public void setCsvcestado(String csvcestado) {
        this.csvcestado = csvcestado;
    }

    /**
     * @return
     */
    public String getCsvcestado() {
        return csvcestado;
    }

    /**
     * @param csvncodinv
     */
    public void setCsvncodinv(Integer csvncodinv) {
        this.csvncodinv = csvncodinv;
    }

    /**
     * @return
     */
    public Integer getCsvncodinv() {
        return csvncodinv;
    }

    /**
     * @param csvntipcon
     */
    public void setCsvntipcon(Integer csvntipcon) {
        this.csvntipcon = csvntipcon;
    }

    /**
     * @return
     */
    public Integer getCsvntipcon() {
        return csvntipcon;
    }

    /**
     * @param csvccups
     */
    public void setCsvccups(String csvccups) {
        this.csvccups = csvccups;
    }

    /**
     * @return
     */
    public String getCsvccups() {
        return csvccups;
    }

    /**
     * @param csvcswpaqu
     */
    public void setCsvcswpaqu(String csvcswpaqu) {
        this.csvcswpaqu = csvcswpaqu;
    }

    /**
     * @return
     */
    public String getCsvcswpaqu() {
        return csvcswpaqu;
    }

    /**
     * @param csvcsollot
     */
    public void setCsvcsollot(String csvcsollot) {
        this.csvcsollot = csvcsollot;
    }

    /**
     * @return
     */
    public String getCsvcsollot() {
        return csvcsollot;
    }

    /**
     * @param csvnedamin
     */
    public void setCsvnedamin(Integer csvnedamin) {
        this.csvnedamin = csvnedamin;
    }

    /**
     * @return
     */
    public Integer getCsvnedamin() {
        return csvnedamin;
    }

    /**
     * @param csvnedamax
     */
    public void setCsvnedamax(Integer csvnedamax) {
        this.csvnedamax = csvnedamax;
    }

    /**
     * @return
     */
    public Integer getCsvnedamax() {
        return csvnedamax;
    }

    /**
     * @param csvcsexo
     */
    public void setCsvcsexo(String csvcsexo) {
        this.csvcsexo = csvcsexo;
    }

    /**
     * @return
     */
    public String getCsvcsexo() {
        return csvcsexo;
    }

    /**
     * @param csvntiphis
     */
    public void setCsvntiphis(Integer csvntiphis) {
        this.csvntiphis = csvntiphis;
    }

    /**
     * @return
     */
    public Integer getCsvntiphis() {
        return csvntiphis;
    }

    /**
     * @param cirujanoSelect
     */
    public void setCirujanoSelect(String cirujanoSelect) {
        this.cirujanoSelect = cirujanoSelect;
    }

    /**
     * @return
     */
    public String getCirujanoSelect() {
        return cirujanoSelect;
    }


    /**
     * @param csvcnombre2
     */
    public void setCsvcnombre2(String csvcnombre2) {
        this.csvcnombre2 = csvcnombre2;
    }

    /**
     * @return
     */
    public String getCsvcnombre2() {
        return csvcnombre2;
    }

    /**
     * @param csvcnombre3
     */
    public void setCsvcnombre3(String csvcnombre3) {
        this.csvcnombre3 = csvcnombre3;
    }

    /**
     * @return
     */
    public String getCsvcnombre3() {
        return csvcnombre3;
    }

    /**
     * @param csvcopera1
     */
    public void setCsvcopera1(String csvcopera1) {
        this.csvcopera1 = csvcopera1;
    }

    /**
     * @return
     */
    public String getCsvcopera1() {
        return csvcopera1;
    }

    /**
     * @param csvcopera2
     */
    public void setCsvcopera2(String csvcopera2) {
        this.csvcopera2 = csvcopera2;
    }

    /**
     * @return
     */
    public String getCsvcopera2() {
        return csvcopera2;
    }

    public void setCsvccodcups(String csvccodcups) {
        this.csvccodcups = csvccodcups;
    }

    public String getCsvccodcups() {
        return csvccodcups;
    }


    public void setNombreServicios(String nombreServicios) {
        this.nombreServicios = nombreServicios;
    }

    public String getNombreServicios() {
        return nombreServicios;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setAgregado(boolean agregado) {
        this.agregado = agregado;
    }

    public boolean isAgregado() {
        return agregado;
    }

    public void setFechaAgregado(Date fechaAgregado) {
        this.fechaAgregado = fechaAgregado;
    }

    public Date getFechaAgregado() {
        return fechaAgregado;
    }

    public void setOperadorAgregado(String operadorAgregado) {
        this.operadorAgregado = operadorAgregado;
    }

    public String getOperadorAgregado() {
        return operadorAgregado;
    }

    public void setClinicaAgregado(Integer clinicaAgregado) {
        this.clinicaAgregado = clinicaAgregado;
    }

    public Integer getClinicaAgregado() {
        return clinicaAgregado;
    }

    public void setTipoServicioAgregado(String tipoServicioAgregado) {
        this.tipoServicioAgregado = tipoServicioAgregado;
    }

    public String getTipoServicioAgregado() {
        return tipoServicioAgregado;
    }

    public void setWtipcito(String wtipcito) {
        this.wtipcito = wtipcito;
    }

    public String getWtipcito() {
     wtipcito = "";
        if(csvntiphis != null){
            if(csvntiphis.equals(IConstantes.HISTORIA_PROCEDIMIENTO_CITOLOGIA_TOMA)){
                wtipcito = "Convencional";
            }
            
            if(csvntiphis.equals(IConstantes.HISTORIA_PROCEDIMIENTO_VPH_TOMA)){
                wtipcito = "VPH";
            }
            
            if(csvntiphis.equals(IConstantes.HISTORIA_PROCEDIMIENTO_CITOLOGIA_TOMA_BASELIQUIDA)){
                wtipcito = "Base Liquida";
            }     
            
            if(csvntiphis.equals(IConstantes.HISTORIA_LECTURA_CITOLOGIA_CONVENCIONAL)){
                wtipcito = "Lectura Convencional";
            }    
            
            if(csvntiphis.equals(IConstantes.HISTORIA_LECTURA_CITOLOGIA_BASE_LIQUIDA)){
                wtipcito = "Lectura Base Liquida";
            }    
            
            if(csvntiphis.equals(IConstantes.HISTORIA_LECTURA_VPH_BASE_LIQUIDA)){
                wtipcito = "Lectura VPH";
            }    
        }
    
        return wtipcito;
    }

    public void setCsvntipage(Integer csvntipage) {
        this.csvntipage = csvntipage;
    }

    public Integer getCsvntipage() {
        return csvntipage;
    }

    public void setCsvcteleorie(String csvcteleorie) {
        this.csvcteleorie = csvcteleorie;
    }

    public String getCsvcteleorie() {
        return csvcteleorie;
    }

    public void setCsvcaplicons(String csvcaplicons) {
        this.csvcaplicons = csvcaplicons;
    }

    public String getCsvcaplicons() {
        return csvcaplicons;
    }

    public void setCsvcpruerapi(Integer csvcpruerapi) {
        this.csvcpruerapi = csvcpruerapi;
    }

    public Integer getCsvcpruerapi() {
        return csvcpruerapi;
    }

    public void setCsvcrelecost(String csvcrelecost) {
        this.csvcrelecost = csvcrelecost;
    }

    public String getCsvcrelecost() {
        return csvcrelecost;
    }

    public void setCsvctipomat(String csvctipomat) {
        this.csvctipomat = csvctipomat;
    }

    public String getCsvctipomat() {
        return csvctipomat;
    }

    public void setCsvcareauso(String csvcareauso) {
        this.csvcareauso = csvcareauso;
    }

    public String getCsvcareauso() {
        return csvcareauso;
    }

   
}
