package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cpservxsal generated by hbm2java
 */
public class

Cpservxsal implements java.io.Serializable {


    private CpservxsalId id;
    private String cspcusuar;
    private Date cspdfecreg;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cpservxsal() {
    }

    /** constructor with id */
    public
    // HS == CpservxsalId


    Cpservxsal(CpservxsalId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CpservxsalId getId() {
        return this.id;
    }

    public void setId(CpservxsalId id) {
        this.id = id;
    }


    public String getCspcusuar() {
        return this.cspcusuar;
    }

    public void setCspcusuar(String cspcusuar) {
        this.cspcusuar = cspcusuar;
    }


    public Date getCspdfecreg() {
        return this.cspdfecreg;
    }

    public void setCspdfecreg(Date cspdfecreg) {
        this.cspdfecreg = cspdfecreg;
    }


    public String getCspcservic() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCspcservic();
    }

    public void setCspcservic(String cspcservic) {
        if (this.id == null) {
            this.id = new CpservxsalId();
        }
        this.id.setCspcservic(cspcservic);
    }

    public Integer getCspnsalesp() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCspnsalesp();
    }

    public void setCspnsalesp(Integer cspnsalesp) {
        if (this.id == null) {
            this.id = new CpservxsalId();
        }
        this.id.setCspnsalesp(cspnsalesp);
    }

    public Integer getCspnclinic() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCspnclinic();
    }

    public void setCspnclinic(Integer cspnclinic) {
        if (this.id == null) {
            this.id = new CpservxsalId();
        }
        this.id.setCspnclinic(cspnclinic);
    }


}
