package org.profamilia.hc.model.dto;


/**
 * CpservxsalId generated by hbm2java
 */
public class

CpservxsalId implements java.io.Serializable {


    private String cspcservic;
    private Integer cspnsalesp;
    private Integer cspnclinic;


    // Constructors

    /** default constructor */
    public CpservxsalId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getCspcservic() {
        return this.cspcservic;
    }

    public void setCspcservic(String cspcservic) {
        this.cspcservic = cspcservic;
    }


    public Integer getCspnsalesp() {
        return this.cspnsalesp;
    }

    public void setCspnsalesp(Integer cspnsalesp) {
        this.cspnsalesp = cspnsalesp;
    }


    public Integer getCspnclinic() {
        return this.cspnclinic;
    }

    public void setCspnclinic(Integer cspnclinic) {
        this.cspnclinic = cspnclinic;
    }


    // no tiene llave compuesta.


}
