package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;
import java.util.List;
import java.util.Set;


/**
 * Cptarxprof generated by hbm2java
 */
public class

Cptarxprof implements java.io.Serializable {

    private CptarxprofId id;
    private BigDecimal ctaatarpar;
    private BigDecimal ctaatarcre;
    private String ctacusuari;
    private Date ctadfecreg;
    private Date ctadfecmod;
    private BigDecimal ctaaporadm;
    private String ctacinclhr;
    private String ctacestado;
    private String ctacusumod;
    private String ctacpriori;
    private Integer version;

    /** nullable persistent field */
    private org.profamilia.hc.model.dto.Cpprofesio cpprofesio;

    /** nullable persistent field */
    private org.profamilia.hc.model.dto.Cpservicio cpservicio;



    // Constructors

    /** default constructor */
    public Cptarxprof() {
    
        cpprofesio = new Cpprofesio();
        cpservicio = new Cpservicio();
    }


    /**
     * @param id
     */
    public void setId(CptarxprofId id) {
        this.id = id;
    }

    /**
     * @return
     */
    public CptarxprofId getId() {
        return id;
    }

    /**
     * @param ctaatarpar
     */
    public void setCtaatarpar(BigDecimal ctaatarpar) {
        this.ctaatarpar = ctaatarpar;
    }

    /**
     * @return
     */
    public BigDecimal getCtaatarpar() {
        return ctaatarpar;
    }

    /**
     * @param ctaatarcre
     */
    public void setCtaatarcre(BigDecimal ctaatarcre) {
        this.ctaatarcre = ctaatarcre;
    }

    /**
     * @return
     */
    public BigDecimal getCtaatarcre() {
        return ctaatarcre;
    }

    /**
     * @param ctacusuari
     */
    public void setCtacusuari(String ctacusuari) {
        this.ctacusuari = ctacusuari;
    }

    /**
     * @return
     */
    public String getCtacusuari() {
        return ctacusuari;
    }

    /**
     * @param ctadfecreg
     */
    public void setCtadfecreg(Date ctadfecreg) {
        this.ctadfecreg = ctadfecreg;
    }

    /**
     * @return
     */
    public Date getCtadfecreg() {
        return ctadfecreg;
    }

    /**
     * @param ctadfecmod
     */
    public void setCtadfecmod(Date ctadfecmod) {
        this.ctadfecmod = ctadfecmod;
    }

    /**
     * @return
     */
    public Date getCtadfecmod() {
        return ctadfecmod;
    }

    /**
     * @param ctaaporadm
     */
    public void setCtaaporadm(BigDecimal ctaaporadm) {
        this.ctaaporadm = ctaaporadm;
    }

    /**
     * @return
     */
    public BigDecimal getCtaaporadm() {
        return ctaaporadm;
    }

    /**
     * @param ctacinclhr
     */
    public void setCtacinclhr(String ctacinclhr) {
        this.ctacinclhr = ctacinclhr;
    }

    /**
     * @return
     */
    public String getCtacinclhr() {
        return ctacinclhr;
    }

    /**
     * @param ctacestado
     */
    public void setCtacestado(String ctacestado) {
        this.ctacestado = ctacestado;
    }

    /**
     * @return
     */
    public String getCtacestado() {
        return ctacestado;
    }

    /**
     * @param ctacusumod
     */
    public void setCtacusumod(String ctacusumod) {
        this.ctacusumod = ctacusumod;
    }

    /**
     * @return
     */
    public String getCtacusumod() {
        return ctacusumod;
    }

    /**
     * @param ctacpriori
     */
    public void setCtacpriori(String ctacpriori) {
        this.ctacpriori = ctacpriori;
    }

    /**
     * @return
     */
    public String getCtacpriori() {
        return ctacpriori;
    }

    /**
     * @param version
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * @return
     */
    public Integer getVersion() {
        return version;
    }

    public void setCpprofesio(Cpprofesio cpprofesio) {
        this.cpprofesio = cpprofesio;
    }

    public Cpprofesio getCpprofesio() {
        return cpprofesio;
    }

    public void setCpservicio(Cpservicio cpservicio) {
        this.cpservicio = cpservicio;
    }

    public Cpservicio getCpservicio() {
        return cpservicio;
    }
}
