package org.profamilia.hc.model.dto;

import java.math.BigDecimal;


/**
 * CptarxprofId generated by hbm2java
 */
public class

CptarxprofId implements java.io.Serializable {


    private Integer ctanclinic;
    private BigDecimal ctanprofes;
    private String ctacservic;


    // Constructors

    /** default constructor */
    public CptarxprofId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCtanclinic() {
        return this.ctanclinic;
    }

    public void setCtanclinic(Integer ctanclinic) {
        this.ctanclinic = ctanclinic;
    }


    public BigDecimal getCtanprofes() {
        return this.ctanprofes;
    }

    public void setCtanprofes(BigDecimal ctanprofes) {
        this.ctanprofes = ctanprofes;
    }


    public String getCtacservic() {
        return this.ctacservic;
    }

    public void setCtacservic(String ctacservic) {
        this.ctacservic = ctacservic;
    }


    // no tiene llave compuesta.


}
