package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cptipodocu generated by hbm2java
 */
public class

Cptipodocu implements java.io.Serializable {


    private Integer ctdnnumero;
    private String ctdcdescri;
    private Date ctddfecreg;
    private String ctdcusuar;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cptipodocu() {
    }

    /** constructor with id */
    public
    // HS == short


    Cptipodocu(Integer ctdnnumero) {
        this.ctdnnumero = ctdnnumero;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCtdnnumero() {
        return this.ctdnnumero;
    }

    public void setCtdnnumero(Integer ctdnnumero) {
        this.ctdnnumero = ctdnnumero;
    }


    public String getCtdcdescri() {
        return this.ctdcdescri;
    }

    public void setCtdcdescri(String ctdcdescri) {
        this.ctdcdescri = ctdcdescri;
    }


    public Date getCtddfecreg() {
        return this.ctddfecreg;
    }

    public void setCtddfecreg(Date ctddfecreg) {
        this.ctddfecreg = ctddfecreg;
    }


    public String getCtdcusuar() {
        return this.ctdcusuar;
    }

    public void setCtdcusuar(String ctdcusuar) {
        this.ctdcusuar = ctdcusuar;
    }


    // no tiene llave compuesta.


}
