package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Cptipconcl generated by hbm2java
 */
public class Cptipconcl implements java.io.Serializable {


    private Integer ctlncodigo;
    private String ctlcdescri;
    private Integer ctlnnumpro;
    private String ctlcvalora;
    private String ctlcsumcuo;
    private String ctlcestadi;
    private String ctlchistor;
    private String ctlcusuar;
    private Date ctldfecreg;
    private BigDecimal ctlaporadm;
    private BigDecimal ctlaporemp;
    private String ctlcinclhr;
    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cptipconcl() {
    }

    /** constructor with id */
    public
    // HS == short


    Cptipconcl(Integer ctlncodigo) {
        this.ctlncodigo = ctlncodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCtlncodigo() {
        return this.ctlncodigo;
    }

    public void setCtlncodigo(Integer ctlncodigo) {
        this.ctlncodigo = ctlncodigo;
    }


    public String getCtlcdescri() {
        return this.ctlcdescri;
    }

    public void setCtlcdescri(String ctlcdescri) {
        this.ctlcdescri = ctlcdescri;
    }


    public Integer getCtlnnumpro() {
        return this.ctlnnumpro;
    }

    public void setCtlnnumpro(Integer ctlnnumpro) {
        this.ctlnnumpro = ctlnnumpro;
    }


    public String getCtlcvalora() {
        return this.ctlcvalora;
    }

    public void setCtlcvalora(String ctlcvalora) {
        this.ctlcvalora = ctlcvalora;
    }


    public String getCtlcsumcuo() {
        return this.ctlcsumcuo;
    }

    public void setCtlcsumcuo(String ctlcsumcuo) {
        this.ctlcsumcuo = ctlcsumcuo;
    }


    public String getCtlcestadi() {
        return this.ctlcestadi;
    }

    public void setCtlcestadi(String ctlcestadi) {
        this.ctlcestadi = ctlcestadi;
    }


    public String getCtlchistor() {
        return this.ctlchistor;
    }

    public void setCtlchistor(String ctlchistor) {
        this.ctlchistor = ctlchistor;
    }


    public String getCtlcusuar() {
        return this.ctlcusuar;
    }

    public void setCtlcusuar(String ctlcusuar) {
        this.ctlcusuar = ctlcusuar;
    }


    public Date getCtldfecreg() {
        return this.ctldfecreg;
    }

    public void setCtldfecreg(Date ctldfecreg) {
        this.ctldfecreg = ctldfecreg;
    }


    public BigDecimal getCtlaporadm() {
        return this.ctlaporadm;
    }

    public void setCtlaporadm(BigDecimal ctlaporadm) {
        this.ctlaporadm = ctlaporadm;
    }


    public BigDecimal getCtlaporemp() {
        return this.ctlaporemp;
    }

    public void setCtlaporemp(BigDecimal ctlaporemp) {
        this.ctlaporemp = ctlaporemp;
    }

    public String getCtlcinclhr() {
        return this.ctlcinclhr;
    }

    public void setCtlcinclhr(String ctlcinclhr) {
        this.ctlcinclhr = ctlcinclhr;
    }


    // no tiene llave compuesta.


}
