package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Cptipoprof generated by hbm2java
 */
public class Cptipoprof implements java.io.Serializable {


    private BigDecimal ctpncodigo;
    private String ctpcdescri;
    private String ctpcusuar;
    private Date ctpdfecreg;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cptipoprof() {
    }

    /** constructor with id */
    public
    // HS == short


    Cptipoprof(BigDecimal ctpncodigo) {
        this.ctpncodigo = ctpncodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    /**
     * @return
     */
    public BigDecimal getCtpncodigo() {
        return this.ctpncodigo;
    }

    /**
     * @param ctpncodigo
     */
    public void setCtpncodigo(BigDecimal ctpncodigo) {
        this.ctpncodigo = ctpncodigo;
    }


    /**
     * @return
     */
    public String getCtpcdescri() {
        return this.ctpcdescri;
    }

    /**
     * @param ctpcdescri
     */
    public void setCtpcdescri(String ctpcdescri) {
        this.ctpcdescri = ctpcdescri;
    }


    /**
     * @return
     */
    public String getCtpcusuar() {
        return this.ctpcusuar;
    }

    /**
     * @param ctpcusuar
     */
    public void setCtpcusuar(String ctpcusuar) {
        this.ctpcusuar = ctpcusuar;
    }


    /**
     * @return
     */
    public Date getCtpdfecreg() {
        return this.ctpdfecreg;
    }

    /**
     * @param ctpdfecreg
     */
    public void setCtpdfecreg(Date ctpdfecreg) {
        this.ctpdfecreg = ctpdfecreg;
    }


    // no tiene llave compuesta.


}

