package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Cptipoprof generated by hbm2java
 */
public class Cptipoespe implements java.io.Serializable {


    private Integer ctencodigo;
    private String ctecdescri;
    private String ctecusuar;
    private Date ctedfecreg;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cptipoespe() {
    }

    public void setCtencodigo(Integer ctencodigo) {
        this.ctencodigo = ctencodigo;
    }

    public Integer getCtencodigo() {
        return ctencodigo;
    }

    public void setCtecdescri(String ctecdescri) {
        this.ctecdescri = ctecdescri;
    }

    public String getCtecdescri() {
        return ctecdescri;
    }

    public void setCtecusuar(String ctecusuar) {
        this.ctecusuar = ctecusuar;
    }

    public String getCtecusuar() {
        return ctecusuar;
    }

    public void setCtedfecreg(Date ctedfecreg) {
        this.ctedfecreg = ctedfecreg;
    }

    public Date getCtedfecreg() {
        return ctedfecreg;
    }
}

