package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cpusuxclin generated by hbm2java
 */
public class Cpusuxclin implements java.io.Serializable {


    private CpusuxclinId id;
    private Integer cucndefaul;
    private String cuccgrabad;
    private Date cucdfecgra;

    private Integer version;


    // Constructors

    /** default constructor */
    public Cpusuxclin() {
    }


    /**
     * @param id
     */
    public void setId(CpusuxclinId id) {
        this.id = id;
    }

    /**
     * @return
     */
    public CpusuxclinId getId() {
        return id;
    }

    /**
     * @param cucndefaul
     */
    public void setCucndefaul(Integer cucndefaul) {
        this.cucndefaul = cucndefaul;
    }

    /**
     * @return
     */
    public Integer getCucndefaul() {
        return cucndefaul;
    }

    /**
     * @param cuccgrabad
     */
    public void setCuccgrabad(String cuccgrabad) {
        this.cuccgrabad = cuccgrabad;
    }

    /**
     * @return
     */
    public String getCuccgrabad() {
        return cuccgrabad;
    }

    /**
     * @param cucdfecgra
     */
    public void setCucdfecgra(Date cucdfecgra) {
        this.cucdfecgra = cucdfecgra;
    }

    /**
     * @return
     */
    public Date getCucdfecgra() {
        return cucdfecgra;
    }

    /**
     * @param version
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * @return
     */
    public Integer getVersion() {
        return version;
    }
}
