package org.profamilia.hc.model.dto;


/**
 * CpusuxsalaId generated by hbm2java
 */
public class CpusuxsalaId implements java.io.Serializable {


    private String cuscusuar;
    private Integer cusnclinic;
    private Integer cusnsalesp;


    // Constructors

    /** default constructor */
    public CpusuxsalaId() {
    }


    /**
     * @param cuscusuar
     */
    public void setCuscusuar(String cuscusuar) {
        this.cuscusuar = cuscusuar;
    }

    /**
     * @return
     */
    public String getCuscusuar() {
        return cuscusuar;
    }

    /**
     * @param cusnclinic
     */
    public void setCusnclinic(Integer cusnclinic) {
        this.cusnclinic = cusnclinic;
    }

    /**
     * @return
     */
    public Integer getCusnclinic() {
        return cusnclinic;
    }

    /**
     * @param cusnsalesp
     */
    public void setCusnsalesp(Integer cusnsalesp) {
        this.cusnsalesp = cusnsalesp;
    }

    /**
     * @return
     */
    public Integer getCusnsalesp() {
        return cusnsalesp;
    }
}
