package org.profamilia.hc.model.dto;


/**
 * CpusuxclinId generated by hbm2java
 */
public class

CpusuxclinId implements java.io.Serializable {


    private Integer cucnclinic;
    private String cuccusuari;


    // Constructors

    /** default constructor */
    public CpusuxclinId() {
    }


    /**
     * @param cucnclinic
     */
    public void setCucnclinic(Integer cucnclinic) {
        this.cucnclinic = cucnclinic;
    }

    /**
     * @return
     */
    public Integer getCucnclinic() {
        return cucnclinic;
    }

    /**
     * @param cuccusuari
     */
    public void setCuccusuari(String cuccusuari) {
        this.cuccusuari = cuccusuari;
    }

    /**
     * @return
     */
    public String getCuccusuari() {
        return cuccusuari;
    }
}
