package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Cractoquir generated by hbm2java
 */
public class Cractoquir implements java.io.Serializable {


    private Integer caqncodigo;
    private String caqcdescri;
    private Date caqdfecreg;
    private String caqcusuari;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Cractoquir() {
    }

    /** constructor with id */
    public
    // HS == short


    Cractoquir(Integer caqncodigo) {
        this.caqncodigo = caqncodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    /**
     * @return
     */
    public Integer getCaqncodigo() {
        return this.caqncodigo;
    }

    /**
     * @param caqncodigo
     */
    public void setCaqncodigo(Integer caqncodigo) {
        this.caqncodigo = caqncodigo;
    }


    /**
     * @return
     */
    public String getCaqcdescri() {
        return this.caqcdescri;
    }

    /**
     * @param caqcdescri
     */
    public void setCaqcdescri(String caqcdescri) {
        this.caqcdescri = caqcdescri;
    }


    /**
     * @return
     */
    public Date getCaqdfecreg() {
        return this.caqdfecreg;
    }

    /**
     * @param caqdfecreg
     */
    public void setCaqdfecreg(Date caqdfecreg) {
        this.caqdfecreg = caqdfecreg;
    }


    /**
     * @return
     */
    public String getCaqcusuari() {
        return this.caqcusuari;
    }

    /**
     * @param caqcusuari
     */
    public void setCaqcusuari(String caqcusuari) {
        this.caqcusuari = caqcusuari;
    }


    // no tiene llave compuesta.


}
