package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Crarcconsu generated by hbm2java
 */
public class

Crarcconsu implements java.io.Serializable {


    private CrarcconsuId id;
    private Date cacdfeccon;
    private String cacctipide;
    private BigDecimal cacanumide;
    private Integer cacnconcep;
    private String caccautori;
    private String cacccodcon;
    private Integer cacnfincon;
    private Integer cacncauext;
    private String caccdiagpr;
    private String caccdiagr1;
    private String caccdiagr2;
    private String caccdiagr3;
    private Integer cacntipdia;
    private BigDecimal cacavalcon;
    private BigDecimal cacavalcuo;
    private BigDecimal cacavalnet;
    private Date cacdfecreg;
    private String caccusuari;
    private BigDecimal caclusuario;
    private Integer cacnclinic;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Crarcconsu() {
    }

    /** constructor with id n*/
    public
    // HS == CrarcconsuId


    Crarcconsu(CrarcconsuId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    /**
     * @return
     */
    public CrarcconsuId getId() {
        return this.id;
    }

    /**
     * @param id
     */
    public void setId(CrarcconsuId id) {
        this.id = id;
    }


    /**
     * @return
     */
    public Date getCacdfeccon() {
        return this.cacdfeccon;
    }

    /**
     * @param cacdfeccon
     */
    public void setCacdfeccon(Date cacdfeccon) {
        this.cacdfeccon = cacdfeccon;
    }


    /**
     * @return
     */
    public String getCacctipide() {
        return this.cacctipide;
    }

    /**
     * @param cacctipide
     */
    public void setCacctipide(String cacctipide) {
        this.cacctipide = cacctipide;
    }


    /**
     * @return
     */
    public BigDecimal getCacanumide() {
        return this.cacanumide;
    }

    /**
     * @param cacanumide
     */
    public void setCacanumide(BigDecimal cacanumide) {
        this.cacanumide = cacanumide;
    }


    /**
     * @return
     */
    public Integer getCacnconcep() {
        return this.cacnconcep;
    }

    /**
     * @param cacnconcep
     */
    public void setCacnconcep(Integer cacnconcep) {
        this.cacnconcep = cacnconcep;
    }


    /**
     * @return
     */
    public String getCaccautori() {
        return this.caccautori;
    }

    /**
     * @param caccautori
     */
    public void setCaccautori(String caccautori) {
        this.caccautori = caccautori;
    }


    /**
     * @return
     */
    public String getCacccodcon() {
        return this.cacccodcon;
    }

    /**
     * @param cacccodcon
     */
    public void setCacccodcon(String cacccodcon) {
        this.cacccodcon = cacccodcon;
    }


    /**
     * @return
     */
    public Integer getCacnfincon() {
        return this.cacnfincon;
    }

    /**
     * @param cacnfincon
     */
    public void setCacnfincon(Integer cacnfincon) {
        this.cacnfincon = cacnfincon;
    }


    /**
     * @return
     */
    public Integer getCacncauext() {
        return this.cacncauext;
    }

    /**
     * @param cacncauext
     */
    public void setCacncauext(Integer cacncauext) {
        this.cacncauext = cacncauext;
    }


    /**
     * @return
     */
    public String getCaccdiagpr() {
        return this.caccdiagpr;
    }

    /**
     * @param caccdiagpr
     */
    public void setCaccdiagpr(String caccdiagpr) {
        this.caccdiagpr = caccdiagpr;
    }


    /**
     * @return
     */
    public String getCaccdiagr1() {
        return this.caccdiagr1;
    }

    /**
     * @param caccdiagr1
     */
    public void setCaccdiagr1(String caccdiagr1) {
        this.caccdiagr1 = caccdiagr1;
    }


    /**
     * @return
     */
    public String getCaccdiagr2() {
        return this.caccdiagr2;
    }

    /**
     * @param caccdiagr2
     */
    public void setCaccdiagr2(String caccdiagr2) {
        this.caccdiagr2 = caccdiagr2;
    }


    /**
     * @return
     */
    public String getCaccdiagr3() {
        return this.caccdiagr3;
    }

    /**
     * @param caccdiagr3
     */
    public void setCaccdiagr3(String caccdiagr3) {
        this.caccdiagr3 = caccdiagr3;
    }


    /**
     * @return
     */
    public Integer getCacntipdia() {
        return this.cacntipdia;
    }

    /**
     * @param cacntipdia
     */
    public void setCacntipdia(Integer cacntipdia) {
        this.cacntipdia = cacntipdia;
    }


    /**
     * @return
     */
    public BigDecimal getCacavalcon() {
        return this.cacavalcon;
    }

    /**
     * @param cacavalcon
     */
    public void setCacavalcon(BigDecimal cacavalcon) {
        this.cacavalcon = cacavalcon;
    }


    /**
     * @return
     */
    public BigDecimal getCacavalcuo() {
        return this.cacavalcuo;
    }

    /**
     * @param cacavalcuo
     */
    public void setCacavalcuo(BigDecimal cacavalcuo) {
        this.cacavalcuo = cacavalcuo;
    }


    /**
     * @return
     */
    public BigDecimal getCacavalnet() {
        return this.cacavalnet;
    }

    /**
     * @param cacavalnet
     */
    public void setCacavalnet(BigDecimal cacavalnet) {
        this.cacavalnet = cacavalnet;
    }


    /**
     * @return
     */
    public Date getCacdfecreg() {
        return this.cacdfecreg;
    }

    /**
     * @param cacdfecreg
     */
    public void setCacdfecreg(Date cacdfecreg) {
        this.cacdfecreg = cacdfecreg;
    }


    /**
     * @return
     */
    public String getCaccusuari() {
        return this.caccusuari;
    }

    /**
     * @param caccusuari
     */
    public void setCaccusuari(String caccusuari) {
        this.caccusuari = caccusuari;
    }


    /**
     * @return
     */
    public BigDecimal getCaclusuario() {
        return caclusuario;
    }

    /**
     * @param caclusuario
     */
    public void setCaclusuario(BigDecimal caclusuario) {
        this.caclusuario = caclusuario;
    }

    /**
     * @return
     */
    public Integer getCacnconcli() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCacnconcli();
    }

    /**
     * @param cacnconcli
     */
    public void setCacnconcli(Integer cacnconcli) {
        if (this.id == null) {
            this.id = new CrarcconsuId();
        }
        this.id.setCacnconcli(cacnconcli);
    }

    /**
     * @return
     */
    public Integer getCacnconsec() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCacnconsec();
    }

    /**
     * @param cacnconsec
     */
    public void setCacnconsec(Integer cacnconsec) {
        if (this.id == null) {
            this.id = new CrarcconsuId();
        }
        this.id.setCacnconsec(cacnconsec);
    }

    /**
     * @return
     */
    public Integer getCacnclinic() {
        return cacnclinic;
    }

    /**
     * @param cacnclinic
     */
    public void setCacnclinic(Integer cacnclinic) {
        this.cacnclinic = cacnclinic;
    }


}
