package org.profamilia.hc.model.dto;

/**
 * CrarcproceId generated by hbm2java
 */
public class

CrarcproceId implements java.io.Serializable {


    private Integer capnconcli;
    private Integer capnconsec;


    // Constructors

    /** default constructor */
    public CrarcproceId() {
    }


    /**
     * @param capnconcli
     */
    public void setCapnconcli(Integer capnconcli) {
        this.capnconcli = capnconcli;
    }

    /**
     * @return
     */
    public Integer getCapnconcli() {
        return capnconcli;
    }

    /**
     * @param capnconsec
     */
    public void setCapnconsec(Integer capnconsec) {
        this.capnconsec = capnconsec;
    }

    /**
     * @return
     */
    public Integer getCapnconsec() {
        return capnconsec;
    }
}
