package org.profamilia.hc.model.dto;

import java.math.BigDecimal;

import java.util.Date;


/**
 * Crarcproce generated by hbm2java
 */
public class

Crarcproce implements java.io.Serializable {


    private CrarcproceId id;
    private Date capdfecpro;
    private String capctipide;
    private BigDecimal capanumide;
    private Integer capnconcep;
    private String capcautori;
    private String capccodpro;
    private Integer capnambito;
    private Integer capnfinpro;
    private String capcperate;
    private String capcdiagpr;
    private String capcdiagre;
    private String capccompli;
    private Integer capnrealiz;
    private BigDecimal capavalpro;
    private Date capdfecreg;
    private String capcusuari;
    private BigDecimal caplusuario;
    private Integer capnclinic;

    private Integer version;

    // Constructors

    /** default constructor */
    public Crarcproce() {
    }

    /**
     * @param id
     */
    public void setId(CrarcproceId id) {
        this.id = id;
    }

    /**
     * @return
     */
    public CrarcproceId getId() {
        return id;
    }

    /**
     * @param capdfecpro
     */
    public void setCapdfecpro(Date capdfecpro) {
        this.capdfecpro = capdfecpro;
    }

    /**
     * @return
     */
    public Date getCapdfecpro() {
        return capdfecpro;
    }

    /**
     * @param capctipide
     */
    public void setCapctipide(String capctipide) {
        this.capctipide = capctipide;
    }

    /**
     * @return
     */
    public String getCapctipide() {
        return capctipide;
    }

    /**
     * @param capanumide
     */
    public void setCapanumide(BigDecimal capanumide) {
        this.capanumide = capanumide;
    }

    /**
     * @return
     */
    public BigDecimal getCapanumide() {
        return capanumide;
    }

    /**
     * @param capnconcep
     */
    public void setCapnconcep(Integer capnconcep) {
        this.capnconcep = capnconcep;
    }

    /**
     * @return
     */
    public Integer getCapnconcep() {
        return capnconcep;
    }

    /**
     * @param capcautori
     */
    public void setCapcautori(String capcautori) {
        this.capcautori = capcautori;
    }

    /**
     * @return
     */
    public String getCapcautori() {
        return capcautori;
    }

    /**
     * @param capccodpro
     */
    public void setCapccodpro(String capccodpro) {
        this.capccodpro = capccodpro;
    }

    /**
     * @return
     */
    public String getCapccodpro() {
        return capccodpro;
    }

    /**
     * @param capnambito
     */
    public void setCapnambito(Integer capnambito) {
        this.capnambito = capnambito;
    }

    /**
     * @return
     */
    public Integer getCapnambito() {
        return capnambito;
    }

    /**
     * @param capnfinpro
     */
    public void setCapnfinpro(Integer capnfinpro) {
        this.capnfinpro = capnfinpro;
    }

    /**
     * @return
     */
    public Integer getCapnfinpro() {
        return capnfinpro;
    }

    /**
     * @param capcperate
     */
    public void setCapcperate(String capcperate) {
        this.capcperate = capcperate;
    }

    /**
     * @return
     */
    public String getCapcperate() {
        return capcperate;
    }

    /**
     * @param capcdiagpr
     */
    public void setCapcdiagpr(String capcdiagpr) {
        this.capcdiagpr = capcdiagpr;
    }

    /**
     * @return
     */
    public String getCapcdiagpr() {
        return capcdiagpr;
    }

    /**
     * @param capcdiagre
     */
    public void setCapcdiagre(String capcdiagre) {
        this.capcdiagre = capcdiagre;
    }

    /**
     * @return
     */
    public String getCapcdiagre() {
        return capcdiagre;
    }

    /**
     * @param capccompli
     */
    public void setCapccompli(String capccompli) {
        this.capccompli = capccompli;
    }

    /**
     * @return
     */
    public String getCapccompli() {
        return capccompli;
    }

    /**
     * @param capnrealiz
     */
    public void setCapnrealiz(Integer capnrealiz) {
        this.capnrealiz = capnrealiz;
    }

    /**
     * @return
     */
    public Integer getCapnrealiz() {
        return capnrealiz;
    }

    /**
     * @param capavalpro
     */
    public void setCapavalpro(BigDecimal capavalpro) {
        this.capavalpro = capavalpro;
    }

    /**
     * @return
     */
    public BigDecimal getCapavalpro() {
        return capavalpro;
    }

    /**
     * @param capdfecreg
     */
    public void setCapdfecreg(Date capdfecreg) {
        this.capdfecreg = capdfecreg;
    }

    /**
     * @return
     */
    public Date getCapdfecreg() {
        return capdfecreg;
    }

    /**
     * @param capcusuari
     */
    public void setCapcusuari(String capcusuari) {
        this.capcusuari = capcusuari;
    }

    /**
     * @return
     */
    public String getCapcusuari() {
        return capcusuari;
    }

    /**
     * @param caplusuario
     */
    public void setCaplusuario(BigDecimal caplusuario) {
        this.caplusuario = caplusuario;
    }

    /**
     * @return
     */
    public BigDecimal getCaplusuario() {
        return caplusuario;
    }

    /**
     * @param capnclinic
     */
    public void setCapnclinic(Integer capnclinic) {
        this.capnclinic = capnclinic;
    }

    /**
     * @return
     */
    public Integer getCapnclinic() {
        return capnclinic;
    }

    /**
     * @param version
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * @return
     */
    public Integer getVersion() {
        return version;
    }
}
