package org.profamilia.hc.model.dto;


/**
 * CrarcconsuId generated by hbm2java
 */
public class

CrarcconsuId implements java.io.Serializable {


    private Integer cacnconcli;
    private Integer cacnconsec;


    // Constructors

    /** default constructor */
    public CrarcconsuId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCacnconcli() {
        return this.cacnconcli;
    }

    public void setCacnconcli(Integer cacnconcli) {
        this.cacnconcli = cacnconcli;
    }


    public Integer getCacnconsec() {
        return this.cacnconsec;
    }

    public void setCacnconsec(Integer cacnconsec) {
        this.cacnconsec = cacnconsec;
    }


    // no tiene llave compuesta.


}
