package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Crcausaext generated by hbm2java
 */
public class Crcausaext implements java.io.Serializable {


    private Integer ccancodigo;
    private String ccacdescri;
    private Date ccadfecreg;
    private String ccacusuari;
    private String ccacestado;

    private Integer version;


    // Constructors

    /** default constructor */
    public Crcausaext() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCcancodigo() {
        return this.ccancodigo;
    }

    public void setCcancodigo(Integer ccancodigo) {
        this.ccancodigo = ccancodigo;
    }


    public String getCcacdescri() {
        return this.ccacdescri;
    }

    public void setCcacdescri(String ccacdescri) {
        this.ccacdescri = ccacdescri;
    }


    public Date getCcadfecreg() {
        return this.ccadfecreg;
    }

    public void setCcadfecreg(Date ccadfecreg) {
        this.ccadfecreg = ccadfecreg;
    }


    public String getCcacusuari() {
        return this.ccacusuari;
    }

    public void setCcacusuari(String ccacusuari) {
        this.ccacusuari = ccacusuari;
    }

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }



    // no tiene llave compuesta.


    public void setCcacestado(String ccacestado) {
        this.ccacestado = ccacestado;
    }

    public String getCcacestado() {
        return ccacestado;
    }
}
