package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Crdgncie10 generated by hbm2java
 */
public class Crdgncie10 implements java.io.Serializable {


    private String cdcccodigo;
    private String cdccsimbol;
    private String cdccdescri;
    private String cdccdescri2;
    private String cdccdescri3;
    private String cdccopera1;
    private String cdccopera2;
    private String cdccsexo;
    private String cdccliminf;
    private String cdcclimsup;
    private String cdccnoafec;
    private String cdccobserv;
    private Date cdcdfecreg;
    private String cdccusuari;
    private String cdccnotobl;
    private String cdccestado; 

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Crdgncie10() {
    }

    /** constructor with id */
    public
    // HS == String


    Crdgncie10(String cdcccodigo) {
        this.cdcccodigo = cdcccodigo;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getCdcccodigo() {
        return this.cdcccodigo;
    }

    public void setCdcccodigo(String cdcccodigo) {
        this.cdcccodigo = cdcccodigo;
    }


    public String getCdccsimbol() {
        return this.cdccsimbol;
    }

    public void setCdccsimbol(String cdccsimbol) {
        this.cdccsimbol = cdccsimbol;
    }


    public String getCdccsexo() {
        return this.cdccsexo;
    }

    public void setCdccsexo(String cdccsexo) {
        this.cdccsexo = cdccsexo;
    }


    public String getCdccliminf() {
        return this.cdccliminf;
    }

    public void setCdccliminf(String cdccliminf) {
        this.cdccliminf = cdccliminf;
    }


    public String getCdcclimsup() {
        return this.cdcclimsup;
    }

    public void setCdcclimsup(String cdcclimsup) {
        this.cdcclimsup = cdcclimsup;
    }


    public String getCdccnoafec() {
        return this.cdccnoafec;
    }

    public void setCdccnoafec(String cdccnoafec) {
        this.cdccnoafec = cdccnoafec;
    }


    public String getCdccobserv() {
        return this.cdccobserv;
    }

    public void setCdccobserv(String cdccobserv) {
        this.cdccobserv = cdccobserv;
    }


    public Date getCdcdfecreg() {
        return this.cdcdfecreg;
    }

    public void setCdcdfecreg(Date cdcdfecreg) {
        this.cdcdfecreg = cdcdfecreg;
    }


    public String getCdccusuari() {
        return this.cdccusuari;
    }

    public void setCdccusuari(String cdccusuari) {
        this.cdccusuari = cdccusuari;
    }

    public String getCdccnotobl() {
        return this.cdccnotobl;
    }

    public void setCdccnotobl(String cdccnotobl) {
        this.cdccnotobl = cdccnotobl;
    }


    // no tiene llave compuesta.


    public void setCdccdescri(String cdccdescri) {
        this.cdccdescri = cdccdescri;
    }

    public String getCdccdescri() {
        return cdccdescri;
    }

    public void setCdccdescri2(String cdccdescri2) {
        this.cdccdescri2 = cdccdescri2;
    }

    public String getCdccdescri2() {
        return cdccdescri2;
    }

    public void setCdccdescri3(String cdccdescri3) {
        this.cdccdescri3 = cdccdescri3;
    }

    public String getCdccdescri3() {
        return cdccdescri3;
    }

    public void setCdccopera1(String cdccopera1) {
        this.cdccopera1 = cdccopera1;
    }

    public String getCdccopera1() {
        return cdccopera1;
    }

    public void setCdccopera2(String cdccopera2) {
        this.cdccopera2 = cdccopera2;
    }

    public String getCdccopera2() {
        return cdccopera2;
    }

    public void setCdccestado(String cdccestado) {
        this.cdccestado = cdccestado;
    }

    public String getCdccestado() {
        return cdccestado;
    }
}
