package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Crentadmin generated by hbm2java
 */
public class

Crentadmin implements java.io.Serializable {


    private CrentadminId id;
    private String ceactipent;
    private String ceacnombre;
    private String ceacnumcon;
    private String ceacdespla;
    private String ceacarccon;
    private String ceacarcpro;
    private String ceacarchos;
    private String ceacarcurg;
    private String ceacarcnac;
    private String ceacarcmed;
    private String ceacarcotr;
    private Date ceadfecreg;
    private String ceacusuari;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Crentadmin() {
    }

    /** constructor with id */
    public
    // HS == CrentadminId


    Crentadmin(CrentadminId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CrentadminId getId() {
        return this.id;
    }

    public void setId(CrentadminId id) {
        this.id = id;
    }


    public String getCeactipent() {
        return this.ceactipent;
    }

    public void setCeactipent(String ceactipent) {
        this.ceactipent = ceactipent;
    }


    public String getCeacnombre() {
        return this.ceacnombre;
    }

    public void setCeacnombre(String ceacnombre) {
        this.ceacnombre = ceacnombre;
    }


    public String getCeacnumcon() {
        return this.ceacnumcon;
    }

    public void setCeacnumcon(String ceacnumcon) {
        this.ceacnumcon = ceacnumcon;
    }


    public String getCeacdespla() {
        return this.ceacdespla;
    }

    public void setCeacdespla(String ceacdespla) {
        this.ceacdespla = ceacdespla;
    }


    public String getCeacarccon() {
        return this.ceacarccon;
    }

    public void setCeacarccon(String ceacarccon) {
        this.ceacarccon = ceacarccon;
    }


    public String getCeacarcpro() {
        return this.ceacarcpro;
    }

    public void setCeacarcpro(String ceacarcpro) {
        this.ceacarcpro = ceacarcpro;
    }


    public String getCeacarchos() {
        return this.ceacarchos;
    }

    public void setCeacarchos(String ceacarchos) {
        this.ceacarchos = ceacarchos;
    }


    public String getCeacarcurg() {
        return this.ceacarcurg;
    }

    public void setCeacarcurg(String ceacarcurg) {
        this.ceacarcurg = ceacarcurg;
    }


    public String getCeacarcnac() {
        return this.ceacarcnac;
    }

    public void setCeacarcnac(String ceacarcnac) {
        this.ceacarcnac = ceacarcnac;
    }


    public String getCeacarcmed() {
        return this.ceacarcmed;
    }

    public void setCeacarcmed(String ceacarcmed) {
        this.ceacarcmed = ceacarcmed;
    }


    public String getCeacarcotr() {
        return this.ceacarcotr;
    }

    public void setCeacarcotr(String ceacarcotr) {
        this.ceacarcotr = ceacarcotr;
    }


    public Date getCeadfecreg() {
        return this.ceadfecreg;
    }

    public void setCeadfecreg(Date ceadfecreg) {
        this.ceadfecreg = ceadfecreg;
    }


    public String getCeacusuari() {
        return this.ceacusuari;
    }

    public void setCeacusuari(String ceacusuari) {
        this.ceacusuari = ceacusuari;
    }


    public Integer getCeanclinic() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCeanclinic();
    }

    public void setCeanclinic(Integer ceanclinic) {
        if (this.id == null) {
            this.id = new CrentadminId();
        }
        this.id.setCeanclinic(ceanclinic);
    }

    public String getCeaccodigo() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCeaccodigo();
    }

    public void setCeaccodigo(String ceaccodigo) {
        if (this.id == null) {
            this.id = new CrentadminId();
        }
        this.id.setCeaccodigo(ceaccodigo);
    }


}
