package org.profamilia.hc.model.dto;


/**
 * CrentadminId generated by hbm2java
 */
public class

CrentadminId implements java.io.Serializable {


    private Integer ceanclinic;
    private String ceaccodigo;


    // Constructors

    /** default constructor */
    public CrentadminId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCeanclinic() {
        return this.ceanclinic;
    }

    public void setCeanclinic(Integer ceanclinic) {
        this.ceanclinic = ceanclinic;
    }


    public String getCeaccodigo() {
        return this.ceaccodigo;
    }

    public void setCeaccodigo(String ceaccodigo) {
        this.ceaccodigo = ceaccodigo;
    }


    // no tiene llave compuesta.


}
