package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Crfinalcon generated by hbm2java
 */
public class

Crfinalcon implements java.io.Serializable {


    private CrfinalconId id;
    private String cfccdescri;
    private Date cfcdfecreg;
    private String cfccusuari;
    private String cfccestado;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Crfinalcon() {
    }

    /** constructor with id */
    public
    // HS == CrfinalconId


    Crfinalcon(CrfinalconId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CrfinalconId getId() {
        return this.id;
    }

    public void setId(CrfinalconId id) {
        this.id = id;
    }


    public String getCfccdescri() {
        return this.cfccdescri;
    }

    public void setCfccdescri(String cfccdescri) {
        this.cfccdescri = cfccdescri;
    }


    public Date getCfcdfecreg() {
        return this.cfcdfecreg;
    }

    public void setCfcdfecreg(Date cfcdfecreg) {
        this.cfcdfecreg = cfcdfecreg;
    }


    public String getCfccusuari() {
        return this.cfccusuari;
    }

    public void setCfccusuari(String cfccusuari) {
        this.cfccusuari = cfccusuari;
    }


    public String getCfccprocon() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCfccprocon();
    }

    public void setCfccprocon(String cfccprocon) {
        if (this.id == null) {
            this.id = new CrfinalconId();
        }
        this.id.setCfccprocon(cfccprocon);
    }

    public Integer getCfcncodigo() {
        if (this.id == null) {
            return null;
        }
        return this.id.getCfcncodigo();
    }

    public void setCfcncodigo(Integer cfcncodigo) {
        if (this.id == null) {
            this.id = new CrfinalconId();
        }
        this.id.setCfcncodigo(cfcncodigo);
    }


    public void setCfccestado(String cfccestado) {
        this.cfccestado = cfccestado;
    }

    public String getCfccestado() {
        return cfccestado;
    }
}
