package org.profamilia.hc.model.dto;


/**
 * CrfinalconId generated by hbm2java
 */
public class

CrfinalconId implements java.io.Serializable {


    private String cfccprocon;
    private Integer cfcncodigo;


    // Constructors

    /** default constructor */
    public CrfinalconId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getCfccprocon() {
        return this.cfccprocon;
    }

    public void setCfccprocon(String cfccprocon) {
        this.cfccprocon = cfccprocon;
    }


    public Integer getCfcncodigo() {
        return this.cfcncodigo;
    }

    public void setCfcncodigo(Integer cfcncodigo) {
        this.cfcncodigo = cfcncodigo;
    }


    // no tiene llave compuesta.


}
