package org.profamilia.hc.model.dto;

/**
 * Crmedicame generated by hbm2java
 */
public class

Crmedicame implements java.io.Serializable {

    private String cmeccodigo;
    private String cmeccodana;
    private String cmecpriact;
    private String cmecforma;
    private String cmecconcen;
    private String cmecdescri;
    private String cmecunimed;
    private String cmectipmed;
    private Integer version;

    // Variables para la busqueda 
    private String cmecdescri2;
    private String cmecdescri3;
    private String cmecopera1;
    private String cmecopera2;


    /** default constructor */
    public Crmedicame() {
    }


    /**
     * @param cmeccodigo
     */
    public void setCmeccodigo(String cmeccodigo) {
        this.cmeccodigo = cmeccodigo;
    }

    /**
     * @return
     */
    public String getCmeccodigo() {
        return cmeccodigo;
    }

    /**
     * @param cmeccodana
     */
    public void setCmeccodana(String cmeccodana) {
        this.cmeccodana = cmeccodana;
    }

    /**
     * @return
     */
    public String getCmeccodana() {
        return cmeccodana;
    }

    /**
     * @param cmecpriact
     */
    public void setCmecpriact(String cmecpriact) {
        this.cmecpriact = cmecpriact;
    }

    /**
     * @return
     */
    public String getCmecpriact() {
        return cmecpriact;
    }

    /**
     * @param cmecforma
     */
    public void setCmecforma(String cmecforma) {
        this.cmecforma = cmecforma;
    }

    /**
     * @return
     */
    public String getCmecforma() {
        return cmecforma;
    }

    /**
     * @param cmecconcen
     */
    public void setCmecconcen(String cmecconcen) {
        this.cmecconcen = cmecconcen;
    }

    /**
     * @return
     */
    public String getCmecconcen() {
        return cmecconcen;
    }

    /**
     * @param cmecdescri
     */
    public void setCmecdescri(String cmecdescri) {
        this.cmecdescri = cmecdescri;
    }

    /**
     * @return
     */
    public String getCmecdescri() {
        return cmecdescri;
    }

    /**
     * @param cmecunimed
     */
    public void setCmecunimed(String cmecunimed) {
        this.cmecunimed = cmecunimed;
    }

    /**
     * @return
     */
    public String getCmecunimed() {
        return cmecunimed;
    }

    /**
     * @param version
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * @return
     */
    public Integer getVersion() {
        return version;
    }


    /**
     * @param cmecopera1
     */
    public void setCmecopera1(String cmecopera1) {
        this.cmecopera1 = cmecopera1;
    }

    /**
     * @return
     */
    public String getCmecopera1() {
        return cmecopera1;
    }

    /**
     * @param cmecopera2
     */
    public void setCmecopera2(String cmecopera2) {
        this.cmecopera2 = cmecopera2;
    }

    /**
     * @return
     */
    public String getCmecopera2() {
        return cmecopera2;
    }

    /**
     * @param cmectipmed
     */
    public void setCmectipmed(String cmectipmed) {
        this.cmectipmed = cmectipmed;
    }

    /**
     * @return
     */
    public String getCmectipmed() {
        return cmectipmed;
    }

    /**
     * @param cmecdescri2
     */
    public void setCmecdescri2(String cmecdescri2) {
        this.cmecdescri2 = cmecdescri2;
    }

    /**
     * @return
     */
    public String getCmecdescri2() {
        return cmecdescri2;
    }

    /**
     * @param cmecdescri3
     */
    public void setCmecdescri3(String cmecdescri3) {
        this.cmecdescri3 = cmecdescri3;
    }

    /**
     * @return
     */
    public String getCmecdescri3() {
        return cmecdescri3;
    }
}
