package org.profamilia.hc.model.dto;


/**
 * CrregcontrId generated by hbm2java
 */
public class

CrripxclinId implements java.io.Serializable {


    private Integer crinclinic;
    private Integer cringrupo;
    private Integer crinsubgru;
    private String cricservic;


    // Constructors

    /** default constructor */
    public CrripxclinId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCrinclinic() {
        return crinclinic;
    }


    public void setCrinclinic(Integer crinclinic) {
        this.crinclinic = crinclinic;
    }


    public Integer getCringrupo() {
        return cringrupo;
    }


    public void setCringrupo(Integer cringrupo) {
        this.cringrupo = cringrupo;
    }


    public Integer getCrinsubgru() {
        return crinsubgru;
    }


    public void setCrinsubgru(Integer crinsubgru) {
        this.crinsubgru = crinsubgru;
    }


    public String getCricservic() {
        return cricservic;
    }


    public void setCricservic(String cricservic) {
        this.cricservic = cricservic;
    }


    // no tiene llave compuesta.


}
