package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Crregcontr generated by hbm2java
 */
public class Crripsserv implements java.io.Serializable {


    private CrripsservId id;
    private String crscconpro;
    private Integer crsnconcep;
    private Integer crsnfinali;
    private Integer crsnambito;
    private Integer crsncauext;
    private String crscperate;
    private String crscdiagpr;
    private String crscdiagre;
    private Integer crsntipdia;
    private Integer crsnrealiz;
    private Date crsdfecreg;
    private String crscusuari;
    private Date crsdfecmod;
    private String crscusumod;
    private String crscestado;

    private Integer version;

    /**
     * @return the version
     */
    public final Integer getVersion() {
        return version;
    }

    /**
     * @param version the version to set
     */
    public final void setVersion(Integer version) {
        this.version = version;
    }
    // Constructors

    /** default constructor */
    public Crripsserv() {
    }

    /** constructor with id */
    public
    // HS == CrregcontrId


    Crripsserv(CrripsservId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public CrripsservId getId() {
        return this.id;
    }

    public void setId(CrripsservId id) {
        this.id = id;
    }


    public String getCrscconpro() {
        return crscconpro;
    }

    public void setCrscconpro(String crscconpro) {
        this.crscconpro = crscconpro;
    }

    public Integer getCrsnconcep() {
        return crsnconcep;
    }

    public void setCrsnconcep(Integer crsnconcep) {
        this.crsnconcep = crsnconcep;
    }

    public Integer getCrsnfinali() {
        return crsnfinali;
    }

    public void setCrsnfinali(Integer crsnfinali) {
        this.crsnfinali = crsnfinali;
    }

    public Integer getCrsnambito() {
        return crsnambito;
    }

    public void setCrsnambito(Integer crsnambito) {
        this.crsnambito = crsnambito;
    }

    public Integer getCrsncauext() {
        return crsncauext;
    }

    public void setCrsncauext(Integer crsncauext) {
        this.crsncauext = crsncauext;
    }

    public String getCrscperate() {
        return crscperate;
    }

    public void setCrscperate(String crscperate) {
        this.crscperate = crscperate;
    }

    public String getCrscdiagpr() {
        return crscdiagpr;
    }

    public void setCrscdiagpr(String crscdiagpr) {
        this.crscdiagpr = crscdiagpr;
    }

    public String getCrscdiagre() {
        return crscdiagre;
    }

    public void setCrscdiagre(String crscdiagre) {
        this.crscdiagre = crscdiagre;
    }

    public Integer getCrsntipdia() {
        return crsntipdia;
    }

    public void setCrsntipdia(Integer crsntipdia) {
        this.crsntipdia = crsntipdia;
    }

    public Integer getCrsnrealiz() {
        return crsnrealiz;
    }

    public void setCrsnrealiz(Integer crsnrealiz) {
        this.crsnrealiz = crsnrealiz;
    }

    public Date getCrsdfecreg() {
        return crsdfecreg;
    }

    public void setCrsdfecreg(Date crsdfecreg) {
        this.crsdfecreg = crsdfecreg;
    }

    public String getCrscusuari() {
        return crscusuari;
    }

    public void setCrscusuari(String crscusuari) {
        this.crscusuari = crscusuari;
    }

    public Date getCrsdfecmod() {
        return crsdfecmod;
    }

    public void setCrsdfecmod(Date crsdfecmod) {
        this.crsdfecmod = crsdfecmod;
    }

    public String getCrscusumod() {
        return crscusumod;
    }

    public void setCrscusumod(String crscusumod) {
        this.crscusumod = crscusumod;
    }


    public void setCrscestado(String crscestado) {
        this.crscestado = crscestado;
    }

    public String getCrscestado() {
        return crscestado;
    }
}
