package org.profamilia.hc.model.dto;


/**
 * CrripsservId generated by hbm2java
 */
public class CrripsservId implements java.io.Serializable {

    private Integer crsngrupo;
    private Integer crsnsubgru;
    private String crscservic;


    // Constructors

    /** default constructor */
    public CrripsservId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public Integer getCrsngrupo() {
        return crsngrupo;
    }


    public void setCrsngrupo(Integer crsngrupo) {
        this.crsngrupo = crsngrupo;
    }


    public Integer getCrsnsubgru() {
        return crsnsubgru;
    }


    public void setCrsnsubgru(Integer crsnsubgru) {
        this.crsnsubgru = crsnsubgru;
    }


    public String getCrscservic() {
        return crscservic;
    }


    public void setCrscservic(String crscservic) {
        this.crscservic = crscservic;
    }


    // no tiene llave compuesta.


}
