package org.profamilia.hc.model.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cvcontrato generated by hbm2java
 */

public class Cvcontrato implements java.io.Serializable {


	
	private CvcontratoId id;
	private String ccncdescri;
	private BigDecimal ccnanit;
	private Date ccndfecreg;
	private Date ccnthorreg;
	private Date ccndfecini;
	private Date ccndfecfin;
	private BigDecimal ccnavaltot;
	private BigDecimal ccnavalcub;
	private Integer ccnnswcont;
	private String ccncusuar;
	private String ccncporcen;
	private String ccncregime;
	private String ccnccodsgs;
	private String ccncobserv;
	private String ccncestado;
	private Integer ccnnnumcon;
	private String ccncdirecc;
	private String ccnctelefo;
	private String ccncciudad;
	private String ccncdepart;
	private String ccncfax;
	private Integer ccnndigver;
	private BigDecimal ccnndonant;
	private Integer ccnncopfac;
	private String ccnccapita;
	private String ccncactite;
	private Integer ccnnclient;
	private Integer ccnnswalca;	

	
	// Constructors

	/** default constructor */
	public Cvcontrato() {
	}


    /**
     * @param id
     */
    public void setId(CvcontratoId id) {
        this.id = id;
    }

    /**
     * @return
     */
    public CvcontratoId getId() {
        return id;
    }

    /**
     * @param ccncdescri
     */
    public void setCcncdescri(String ccncdescri) {
        this.ccncdescri = ccncdescri;
    }

    /**
     * @return
     */
    public String getCcncdescri() {
        return ccncdescri;
    }

    /**
     * @param ccnanit
     */
    public void setCcnanit(BigDecimal ccnanit) {
        this.ccnanit = ccnanit;
    }

    /**
     * @return
     */
    public BigDecimal getCcnanit() {
        return ccnanit;
    }

    /**
     * @param ccndfecreg
     */
    public void setCcndfecreg(Date ccndfecreg) {
        this.ccndfecreg = ccndfecreg;
    }

    /**
     * @return
     */
    public Date getCcndfecreg() {
        return ccndfecreg;
    }

    /**
     * @param ccnthorreg
     */
    public void setCcnthorreg(Date ccnthorreg) {
        this.ccnthorreg = ccnthorreg;
    }

    /**
     * @return
     */
    public Date getCcnthorreg() {
        return ccnthorreg;
    }

    /**
     * @param ccndfecini
     */
    public void setCcndfecini(Date ccndfecini) {
        this.ccndfecini = ccndfecini;
    }

    /**
     * @return
     */
    public Date getCcndfecini() {
        return ccndfecini;
    }

    /**
     * @param ccndfecfin
     */
    public void setCcndfecfin(Date ccndfecfin) {
        this.ccndfecfin = ccndfecfin;
    }

    /**
     * @return
     */
    public Date getCcndfecfin() {
        return ccndfecfin;
    }

    /**
     * @param ccnavaltot
     */
    public void setCcnavaltot(BigDecimal ccnavaltot) {
        this.ccnavaltot = ccnavaltot;
    }

    /**
     * @return
     */
    public BigDecimal getCcnavaltot() {
        return ccnavaltot;
    }

    /**
     * @param ccnavalcub
     */
    public void setCcnavalcub(BigDecimal ccnavalcub) {
        this.ccnavalcub = ccnavalcub;
    }

    /**
     * @return
     */
    public BigDecimal getCcnavalcub() {
        return ccnavalcub;
    }

    /**
     * @param ccnnswcont
     */
    public void setCcnnswcont(Integer ccnnswcont) {
        this.ccnnswcont = ccnnswcont;
    }

    /**
     * @return
     */
    public Integer getCcnnswcont() {
        return ccnnswcont;
    }

    /**
     * @param ccncusuar
     */
    public void setCcncusuar(String ccncusuar) {
        this.ccncusuar = ccncusuar;
    }

    /**
     * @return
     */
    public String getCcncusuar() {
        return ccncusuar;
    }

    /**
     * @param ccncporcen
     */
    public void setCcncporcen(String ccncporcen) {
        this.ccncporcen = ccncporcen;
    }

    /**
     * @return
     */
    public String getCcncporcen() {
        return ccncporcen;
    }

    /**
     * @param ccncregime
     */
    public void setCcncregime(String ccncregime) {
        this.ccncregime = ccncregime;
    }

    /**
     * @return
     */
    public String getCcncregime() {
        return ccncregime;
    }

    /**
     * @param ccnccodsgs
     */
    public void setCcnccodsgs(String ccnccodsgs) {
        this.ccnccodsgs = ccnccodsgs;
    }

    /**
     * @return
     */
    public String getCcnccodsgs() {
        return ccnccodsgs;
    }

    /**
     * @param ccncobserv
     */
    public void setCcncobserv(String ccncobserv) {
        this.ccncobserv = ccncobserv;
    }

    /**
     * @return
     */
    public String getCcncobserv() {
        return ccncobserv;
    }

    /**
     * @param ccncestado
     */
    public void setCcncestado(String ccncestado) {
        this.ccncestado = ccncestado;
    }

    /**
     * @return
     */
    public String getCcncestado() {
        return ccncestado;
    }

    /**
     * @param ccnnnumcon
     */
    public void setCcnnnumcon(Integer ccnnnumcon) {
        this.ccnnnumcon = ccnnnumcon;
    }

    /**
     * @return
     */
    public Integer getCcnnnumcon() {
        return ccnnnumcon;
    }

    /**
     * @param ccncdirecc
     */
    public void setCcncdirecc(String ccncdirecc) {
        this.ccncdirecc = ccncdirecc;
    }

    /**
     * @return
     */
    public String getCcncdirecc() {
        return ccncdirecc;
    }

    /**
     * @param ccnctelefo
     */
    public void setCcnctelefo(String ccnctelefo) {
        this.ccnctelefo = ccnctelefo;
    }

    /**
     * @return
     */
    public String getCcnctelefo() {
        return ccnctelefo;
    }

    /**
     * @param ccncciudad
     */
    public void setCcncciudad(String ccncciudad) {
        this.ccncciudad = ccncciudad;
    }

    /**
     * @return
     */
    public String getCcncciudad() {
        return ccncciudad;
    }

    /**
     * @param ccncdepart
     */
    public void setCcncdepart(String ccncdepart) {
        this.ccncdepart = ccncdepart;
    }

    /**
     * @return
     */
    public String getCcncdepart() {
        return ccncdepart;
    }

    /**
     * @param ccncfax
     */
    public void setCcncfax(String ccncfax) {
        this.ccncfax = ccncfax;
    }

    /**
     * @return
     */
    public String getCcncfax() {
        return ccncfax;
    }

    /**
     * @param ccnndigver
     */
    public void setCcnndigver(Integer ccnndigver) {
        this.ccnndigver = ccnndigver;
    }

    /**
     * @return
     */
    public Integer getCcnndigver() {
        return ccnndigver;
    }

    /**
     * @param ccnndonant
     */
    public void setCcnndonant(BigDecimal ccnndonant) {
        this.ccnndonant = ccnndonant;
    }

    /**
     * @return
     */
    public BigDecimal getCcnndonant() {
        return ccnndonant;
    }

    /**
     * @param ccnncopfac
     */
    public void setCcnncopfac(Integer ccnncopfac) {
        this.ccnncopfac = ccnncopfac;
    }

    /**
     * @return
     */
    public Integer getCcnncopfac() {
        return ccnncopfac;
    }

    /**
     * @param ccnccapita
     */
    public void setCcnccapita(String ccnccapita) {
        this.ccnccapita = ccnccapita;
    }

    /**
     * @return
     */
    public String getCcnccapita() {
        return ccnccapita;
    }

    /**
     * @param ccncactite
     */
    public void setCcncactite(String ccncactite) {
        this.ccncactite = ccncactite;
    }

    /**
     * @return
     */
    public String getCcncactite() {
        return ccncactite;
    }

    /**
     * @param ccnnclient
     */
    public void setCcnnclient(Integer ccnnclient) {
        this.ccnnclient = ccnnclient;
    }

    /**
     * @return
     */
    public Integer getCcnnclient() {
        return ccnnclient;
    }

    /**
     * @param ccnnswalca
     */
    public void setCcnnswalca(Integer ccnnswalca) {
        this.ccnnswalca = ccnnswalca;
    }

    /**
     * @return
     */
    public Integer getCcnnswalca() {
        return ccnnswalca;
    }

}
