package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Sapermusua generated by hbm2java
 */
public class

Sapermusua implements java.io.Serializable {

    private SapermusuaId id;
    private String spuchabili;
    private String spucetapa;
    private Date spudfeccre;
    private String spucusucre;
    private String spucaplica;
    private Date spudfecini;
    private Date spudfecfin;
    private Integer version;

    /** nullable persistent field */
    private org.profamilia.hc.model.dto.Saprograma saprograma;

    // Constructors

    /** default constructor */
    public Sapermusua() {
    }

    /** constructor with id */
    public
    // HS == SarolId


    // HS SEPARADOR CONSTRUCTOR

    // Property accessors

    SapermusuaId getId() {
        return this.id;
    }

    public void setId(SapermusuaId id) {
        this.id = id;
    }

    public String getSpucprogra() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSpucprogra();
    }

    public void setSpucprogra(String spucprogra) {
        if (this.id == null) {
            this.id = new SapermusuaId();
        }
        this.id.setSpucprogra(spucprogra);
    }

    public String getSpucusuari() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSpucusuari();
    }

    public void setSpucusuari(String spucusuari) {
        if (this.id == null) {
            this.id = new SapermusuaId();
        }
        this.id.setSpucusuari(spucusuari);
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public final String getSpuchabili() {
        return spuchabili;
    }

    public final void setSpuchabili(String spuchabili) {
        this.spuchabili = spuchabili;
    }

    public final String getSpucetapa() {
        return spucetapa;
    }

    public final void setSpucetapa(String spucetapa) {
        this.spucetapa = spucetapa;
    }

    public final Date getSpudfeccre() {
        return spudfeccre;
    }

    public final void setSpudfeccre(Date spudfeccre) {
        this.spudfeccre = spudfeccre;
    }

    public final String getSpucusucre() {
        return spucusucre;
    }

    public final void setSpucusucre(String spucusucre) {
        this.spucusucre = spucusucre;
    }

    public final String getSpucaplica() {
        return spucaplica;
    }

    public final void setSpucaplica(String spucaplica) {
        this.spucaplica = spucaplica;
    }

    public final Date getSpudfecini() {
        return spudfecini;
    }

    public final void setSpudfecini(Date spudfecini) {
        this.spudfecini = spudfecini;
    }

    public final Date getSpudfecfin() {
        return spudfecfin;
    }

    public final void setSpudfecfin(Date spudfecfin) {
        this.spudfecfin = spudfecfin;
    }

    public void setSaprograma(Saprograma saprograma) {
        this.saprograma = saprograma;
    }

    public Saprograma getSaprograma() {
        return saprograma;
    }
}
