package org.profamilia.hc.model.dto;

/**
 * SarolId generated by hbm2java
 */
public class

SapermrolId implements java.io.Serializable {

    private String sprcrol;
    private String sprcaplica;
    private String sprcprogra;


    // Constructors

    /** default constructor */
    public SapermrolId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getSprcrol() {
        return this.sprcrol;
    }

    public void setSprcrol(String sprcrol) {
        this.sprcrol = sprcrol;
    }

    public String getSprcaplica() {
        return this.sprcaplica;
    }

    public void setSprcaplica(String sprcaplica) {
        this.sprcaplica = sprcaplica;
    }

    public String getSprcprogra() {
        return this.sprcprogra;
    }

    public void setSprcprogra(String sprcprogra) {
        this.sprcprogra = sprcprogra;
    }

    // no tiene llave compuesta.

}
