package org.profamilia.hc.model.dto;

/**
 * SarolId generated by hbm2java
 */
public class

SapermusuaId implements java.io.Serializable {

    private String spucprogra;
    private String spucusuari;


    // Constructors

    /** default constructor */
    public SapermusuaId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getSpucprogra() {
        return this.spucprogra;
    }

    public void setSpucprogra(String spucprogra) {
        this.spucprogra = spucprogra;
    }

    public String getSpucusuari() {
        return this.spucusuari;
    }

    public void setSpucusuari(String spucusuari) {
        this.spucusuari = spucusuari;
    }

    // no tiene llave compuesta.

}
