package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Sapermrol generated by hbm2java
 */
public class Sapermrol implements java.io.Serializable {

    private SapermrolId id;
    private Date sprdfecdef;
    private Date sprdfecfin;
    private String sprcetapa;
    private Integer version;

    /** nullable persistent field */
    private org.profamilia.hc.model.dto.Saprograma saprograma;

    // Constructors

    /** default constructor */
    public Sapermrol() {
    }

    /** constructor with id */
    public
    // HS == SarolId

    Sapermrol(SapermrolId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR

    // Property accessors

    public SapermrolId getId() {
        return this.id;
    }

    public void setId(SapermrolId id) {
        this.id = id;
    }

    public String getSprcrol() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSprcrol();
    }

    public void setSprcrol(String sprcrol) {
        if (this.id == null) {
            this.id = new SapermrolId();
        }
        this.id.setSprcrol(sprcrol);
    }

    public String getSprcaplica() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSprcaplica();
    }

    public void setSprcaplica(String sprcaplica) {
        if (this.id == null) {
            this.id = new SapermrolId();
        }
        this.id.setSprcaplica(sprcaplica);
    }

    public String getSprcprogra() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSprcprogra();
    }

    public void setSprcprogra(String sprcprogra) {
        if (this.id == null) {
            this.id = new SapermrolId();
        }
        this.id.setSprcprogra(sprcprogra);
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public final Date getSprdfecdef() {
        return sprdfecdef;
    }

    public final void setSprdfecdef(Date sprdfecdef) {
        this.sprdfecdef = sprdfecdef;
    }

    public final Date getSprdfecfin() {
        return sprdfecfin;
    }

    public final void setSprdfecfin(Date sprdfecfin) {
        this.sprdfecfin = sprdfecfin;
    }

    public final String getSprcetapa() {
        return sprcetapa;
    }

    public final void setSprcetapa(String sprcetapa) {
        this.sprcetapa = sprcetapa;
    }

    public void setSaprograma(Saprograma saprograma) {
        this.saprograma = saprograma;
    }

    public Saprograma getSaprograma() {
        return saprograma;
    }
}
