package org.profamilia.hc.model.dto;

import java.util.Date;


/**
 * Sarol generated by hbm2java
 */
public class

Sarol implements java.io.Serializable {

    private SarolId id;
    private String srocdescri;
    private Date srodfeccre;
    private String srocusucre;
    private String srocetapa;
    private Integer version;

    // Constructors

    /** default constructor */
    public Sarol() {
    }

    /** constructor with id */
    public
    // HS == SarolId

    Sarol(SarolId id) {
        this.id = id;
    }

    // HS SEPARADOR CONSTRUCTOR

    // Property accessors

    public SarolId getId() {
        return this.id;
    }

    public void setId(SarolId id) {
        this.id = id;
    }

    public Date getSrodfeccre() {
        return this.srodfeccre;
    }

    public void setSrodfeccre(Date srodfeccre) {
        this.srodfeccre = srodfeccre;
    }

    public String getSrocnombre() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSrocnombre();
    }

    public void setSrocnombre(String srocnombre) {
        if (this.id == null) {
            this.id = new SarolId();
        }
        this.id.setSrocnombre(srocnombre);
    }

    public String getSrocaplica() {
        if (this.id == null) {
            return null;
        }
        return this.id.getSrocaplica();
    }

    public void setSrocaplica(String srocaplica) {
        if (this.id == null) {
            this.id = new SarolId();
        }
        this.id.setSrocaplica(srocaplica);
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public final String getSrocdescri() {
        return srocdescri;
    }

    public final void setSrocdescri(String srocdescri) {
        this.srocdescri = srocdescri;
    }

    public final String getSrocusucre() {
        return srocusucre;
    }

    public final void setSrocusucre(String srocusucre) {
        this.srocusucre = srocusucre;
    }

    public final String getSrocetapa() {
        return srocetapa;
    }

    public final void setSrocetapa(String srocetapa) {
        this.srocetapa = srocetapa;
    }

}
