package org.profamilia.hc.model.dto;

/**
 * SarolId generated by hbm2java
 */
public class

SarolId implements java.io.Serializable {

    private String srocnombre;
    private String srocaplica;


    // Constructors

    /** default constructor */
    public SarolId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    /**
     * @param srocnombre
     */
    public void setSrocnombre(String srocnombre) {
        this.srocnombre = srocnombre;
    }

    /**
     * @return
     */
    public String getSrocnombre() {
        return srocnombre;
    }

    /**
     * @param srocaplica
     */
    public void setSrocaplica(String srocaplica) {
        this.srocaplica = srocaplica;
    }

    /**
     * @return
     */
    public String getSrocaplica() {
        return srocaplica;
    }
}
