package org.profamilia.hc.model.dto;

/**
 * SarolId generated by hbm2java
 */
public class

SarolsusuaId implements java.io.Serializable {

    private String srucrol;
    private String srucaplica;
    private String srucusuari;


    // Constructors

    /** default constructor */
    public SarolsusuaId() {
    }


    // HS SEPARADOR CONSTRUCTOR


    // Property accessors


    public String getSrucrol() {
        return this.srucrol;
    }

    public void setSrucrol(String srucrol) {
        this.srucrol = srucrol;
    }

    public String getSrucaplica() {
        return this.srucaplica;
    }

    public void setSrucaplica(String srucaplica) {
        this.srucaplica = srucaplica;
    }

    public String getSrucusuari() {
        return this.srucusuari;
    }

    public void setSrucusuari(String srucusuari) {
        this.srucusuari = srucusuari;
    }

    // no tiene llave compuesta.

}
